import mongoose, { Document, Schema } from "mongoose";

/**
 * Phase 6 — Personal Activity Module.
 *
 * This is the authenticated user's *own* activity timeline, not the
 * platform-wide audit log (that belongs to a later Admin phase). Every
 * event stored here was generated by an action taken by this specific user.
 *
 * Design notes for future expansion (Architecture §13):
 *  - `activityType` is a free-form string enum rather than a Mongoose enum
 *    so new event types can be added by extending ACTIVITY_TYPES below and
 *    emitting from a service — zero schema migration needed.
 *  - `metadata` is a schemaless Mixed field for event-specific payload
 *    (e.g., { ipAddress } on login, { fields } on profile update). Callers
 *    decide what to put here; the Activity query/display layer treats it as
 *    opaque enrichment.
 *  - Index on (userId, createdAt DESC) covers the only real query this
 *    phase ever makes: "most recent activities for user X".
 */

export const ACTIVITY_TYPES = {
  ACCOUNT_CREATED: "account_created",
  LOGIN: "login",
  LOGOUT: "logout",
  PROFILE_UPDATED: "profile_updated",
  PHOTO_UPLOADED: "photo_uploaded",
  PHOTO_REMOVED: "photo_removed",
  PASSWORD_CHANGED: "password_changed",
  PASSWORD_RESET: "password_reset",
} as const;

export type ActivityType = (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];

export type ActivityCategory = "authentication" | "profile" | "security";

export interface IActivity extends Document {
  userId: mongoose.Types.ObjectId;
  activityType: ActivityType;
  title: string;
  description: string;
  category: ActivityCategory;
  metadata?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

const ActivitySchema = new Schema<IActivity>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    activityType: { type: String, required: true },
    title: { type: String, required: true, maxlength: 200 },
    description: { type: String, required: true, maxlength: 500 },
    category: { type: String, required: true, enum: ["authentication", "profile", "security"] },
    metadata: { type: Schema.Types.Mixed },
  },
  { timestamps: true },
);

// Compound index: user-scoped newest-first — the only query shape used by
// GET /api/profile/activity. userId first because queries always scope to
// a single user, createdAt DESC for the sort.
ActivitySchema.index({ userId: 1, createdAt: -1 });

export const Activity = mongoose.model<IActivity>("Activity", ActivitySchema);
