/**
 * city-map-data.ts
 *
 * FRONTEND FALLBACK / OFFLINE LAYER
 *
 * This file provides static city map data used when:
 *   - The backend API is unreachable (no network / dev mode without backend)
 *   - The getCityMapData query has not yet resolved
 *
 * The canonical, live-enriched data comes from the backend endpoint:
 *   GET /environmental/cities/:cityId/map-data
 *
 * To add a new city, append one CityMapData entry to CITY_MAP_DATA below AND
 * add the matching seed entry in backend/src/seed/mapLocations.seed.ts.
 * No other files need to change.
 */

// ─── Interfaces ───────────────────────────────────────────────────────────────

export type LocationCategory =
  "industrial" | "residential" | "commercial" | "park" | "water" | "landmark";

/** A single named location on the city canvas */
export interface MapLocation {
  /** Stable short ID unique within a city */
  id: string;
  /** Human-readable place name */
  name: string;
  /** Land-use / zone type */
  category: LocationCategory;
  /** SVG canvas X position (0–100 %) */
  x: number;
  /** SVG canvas Y position (0–100 %) */
  y: number;
  /**
   * Base pollution level 0–100.
   * On the live path this is overwritten by the API with:
   *   min(100, round(cityAQI × pollutionMultiplier))
   */
  level: number;
  /** Whether a physical sensor node is deployed here */
  sensor: boolean;
  /** Short context blurb for tooltips */
  description: string;
}

/** A named water body rendered as blue dots in the water overlay layer */
export interface WaterBody {
  id: string;
  name: string;
  /** SVG canvas X position (0–100 %) */
  x: number;
  /** SVG canvas Y position (0–100 %) */
  y: number;
}

/** Land-use zone percentages shown in the sidebar panel */
export interface EnvZones {
  residential: number;
  industrial: number;
  commercial: number;
  greenCover: number;
}

/** Full per-city canvas config */
export interface CityMapData {
  cityId: string;
  center: { lat: number; lng: number };
  zoom: number;
  /** Alias kept for backward compat with original map.tsx usage */
  hotspots: MapLocation[];
  waterBodies: WaterBody[];
  zones: EnvZones;
}

// ─── Static data: all 14 cities ───────────────────────────────────────────────

export const CITY_MAP_DATA: Record<string, CityMapData> = {
  // ── AHMEDABAD ──────────────────────────────────────────────────────────────
  ahmedabad: {
    cityId: "ahmedabad",
    center: { lat: 23.0225, lng: 72.5714 },
    zoom: 12,
    waterBodies: [
      { id: "aw1", name: "Sabarmati River", x: 42, y: 38 },
      { id: "aw2", name: "Kankaria Lake", x: 62, y: 72 },
      { id: "aw3", name: "Chandola Lake", x: 70, y: 80 },
    ],
    zones: { residential: 52, industrial: 22, commercial: 18, greenCover: 8 },
    hotspots: [
      {
        id: "a1",
        name: "Naroda GIDC",
        category: "industrial",
        x: 72,
        y: 28,
        level: 92,
        sensor: true,
        description: "Largest GIDC estate; heavy chemicals, dyes & textiles",
      },
      {
        id: "a2",
        name: "Vatva GIDC",
        category: "industrial",
        x: 78,
        y: 64,
        level: 88,
        sensor: true,
        description: "Chemical & pharmaceutical industrial cluster",
      },
      {
        id: "a3",
        name: "Sabarmati Riverfront",
        category: "water",
        x: 44,
        y: 40,
        level: 28,
        sensor: true,
        description: "Revamped riverfront promenade; water quality monitoring station",
      },
      {
        id: "a4",
        name: "CG Road",
        category: "commercial",
        x: 46,
        y: 48,
        level: 58,
        sensor: true,
        description: "Dense commercial corridor with high vehicle load",
      },
      {
        id: "a5",
        name: "Satellite",
        category: "residential",
        x: 34,
        y: 58,
        level: 46,
        sensor: false,
        description: "Upmarket residential township; moderate pollution exposure",
      },
      {
        id: "a6",
        name: "Prahlad Nagar",
        category: "commercial",
        x: 40,
        y: 68,
        level: 54,
        sensor: true,
        description: "IT & retail hub; SEZ-adjacent traffic congestion",
      },
      {
        id: "a7",
        name: "Kankaria Lake",
        category: "water",
        x: 62,
        y: 72,
        level: 24,
        sensor: true,
        description: "Historic 15th-century lake; ongoing water quality restoration",
      },
      {
        id: "a8",
        name: "Odhav Industrial",
        category: "industrial",
        x: 82,
        y: 60,
        level: 78,
        sensor: false,
        description: "Auto-parts & plastics manufacturing zone",
      },
      {
        id: "a9",
        name: "Maninagar",
        category: "residential",
        x: 60,
        y: 62,
        level: 52,
        sensor: false,
        description: "Dense residential area between two GIDCs",
      },
    ],
  },

  // ── BELAGAVI ──────────────────────────────────────────────────────────────
  belagavi: {
    cityId: "belagavi",
    center: { lat: 15.8497, lng: 74.4977 },
    zoom: 13,
    waterBodies: [
      { id: "bw1", name: "Rakaskop Reservoir", x: 62, y: 70 },
      { id: "bw2", name: "Markandeya River", x: 24, y: 62 },
    ],
    zones: { residential: 55, industrial: 18, commercial: 15, greenCover: 12 },
    hotspots: [
      {
        id: "b1",
        name: "Tilakwadi",
        category: "residential",
        x: 36,
        y: 44,
        level: 48,
        sensor: false,
        description: "Central residential neighbourhood; mixed-use traffic hub",
      },
      {
        id: "b2",
        name: "Shahapur",
        category: "residential",
        x: 54,
        y: 38,
        level: 44,
        sensor: false,
        description: "Old city residential quarter; traditional housing fabric",
      },
      {
        id: "b3",
        name: "Udyambag",
        category: "industrial",
        x: 68,
        y: 52,
        level: 72,
        sensor: true,
        description: "Mixed-use industrial estate; foundry & light engineering",
      },
      {
        id: "b4",
        name: "Machhe Industrial Area",
        category: "industrial",
        x: 78,
        y: 28,
        level: 82,
        sensor: true,
        description: "Karnataka SIDCO industrial area; textiles & chemicals",
      },
      {
        id: "b5",
        name: "Belagavi Fort",
        category: "landmark",
        x: 46,
        y: 28,
        level: 34,
        sensor: false,
        description: "16th-century Maratha fort; heritage conservation zone",
      },
      {
        id: "b6",
        name: "Rani Chennamma Circle",
        category: "commercial",
        x: 50,
        y: 46,
        level: 58,
        sensor: true,
        description: "City centre roundabout; high pedestrian & vehicle density",
      },
      {
        id: "b7",
        name: "Vaccine Depot Area",
        category: "commercial",
        x: 42,
        y: 56,
        level: 52,
        sensor: false,
        description: "Healthcare & logistics commercial cluster",
      },
      {
        id: "b8",
        name: "Markandeya River Bank",
        category: "water",
        x: 22,
        y: 68,
        level: 18,
        sensor: true,
        description: "Seasonal river; upstream pollution monitoring point",
      },
    ],
  },

  // ── BENGALURU ─────────────────────────────────────────────────────────────
  bengaluru: {
    cityId: "bengaluru",
    center: { lat: 12.9716, lng: 77.5946 },
    zoom: 12,
    waterBodies: [
      { id: "bgw1", name: "Bellandur Lake", x: 70, y: 68 },
      { id: "bgw2", name: "Ulsoor Lake", x: 52, y: 42 },
      { id: "bgw3", name: "Varthur Lake", x: 80, y: 72 },
    ],
    zones: { residential: 48, industrial: 20, commercial: 24, greenCover: 8 },
    hotspots: [
      {
        id: "bg1",
        name: "Whitefield",
        category: "commercial",
        x: 80,
        y: 42,
        level: 68,
        sensor: true,
        description: "IT corridor & ITPL; heavy commuter traffic on Outer Ring Road",
      },
      {
        id: "bg2",
        name: "Electronic City",
        category: "industrial",
        x: 64,
        y: 80,
        level: 78,
        sensor: true,
        description: "India's first planned IT export zone; high diesel generator load",
      },
      {
        id: "bg3",
        name: "Hebbal",
        category: "commercial",
        x: 38,
        y: 22,
        level: 62,
        sensor: true,
        description: "NH junction flyover node; peak-hour AQI spikes to 180+",
      },
      {
        id: "bg4",
        name: "Koramangala",
        category: "commercial",
        x: 56,
        y: 60,
        level: 56,
        sensor: false,
        description: "Start-up & F&B hub; medium traffic density",
      },
      {
        id: "bg5",
        name: "Peenya",
        category: "industrial",
        x: 24,
        y: 36,
        level: 88,
        sensor: true,
        description: "Largest industrial estate in south India; metals & engineering",
      },
      {
        id: "bg6",
        name: "MG Road",
        category: "commercial",
        x: 48,
        y: 46,
        level: 60,
        sensor: false,
        description: "CBD retail corridor; high foot-fall and congestion",
      },
      {
        id: "bg7",
        name: "Bellandur Lake",
        category: "water",
        x: 70,
        y: 68,
        level: 22,
        sensor: true,
        description: "Largest lake in Bengaluru; foam & fire incidents tracked",
      },
      {
        id: "bg8",
        name: "Marathahalli",
        category: "commercial",
        x: 74,
        y: 52,
        level: 64,
        sensor: false,
        description: "High-density retail & residential corridor",
      },
      {
        id: "bg9",
        name: "Yelahanka",
        category: "residential",
        x: 38,
        y: 14,
        level: 42,
        sensor: false,
        description: "Northern residential suburb; Air Force Station proximity",
      },
    ],
  },

  // ── MUMBAI ────────────────────────────────────────────────────────────────
  mumbai: {
    cityId: "mumbai",
    center: { lat: 19.076, lng: 72.8777 },
    zoom: 12,
    waterBodies: [
      { id: "mw1", name: "Powai Lake", x: 66, y: 26 },
      { id: "mw2", name: "Mahim Bay", x: 26, y: 58 },
      { id: "mw3", name: "Mumbai Harbour", x: 58, y: 68 },
    ],
    zones: { residential: 50, industrial: 20, commercial: 24, greenCover: 6 },
    hotspots: [
      {
        id: "m1",
        name: "Dharavi",
        category: "industrial",
        x: 32,
        y: 52,
        level: 88,
        sensor: true,
        description: "Dense mixed-use area with leather & recycling industries",
      },
      {
        id: "m2",
        name: "Bandra-Kurla Complex",
        category: "commercial",
        x: 58,
        y: 40,
        level: 60,
        sensor: true,
        description: "Prime CBD; Bandra-Worli Sea Link traffic gateway",
      },
      {
        id: "m3",
        name: "Chembur",
        category: "industrial",
        x: 72,
        y: 38,
        level: 84,
        sensor: true,
        description: "Refinery & petrochemical complex; legacy HPCL/BPCL emissions",
      },
      {
        id: "m4",
        name: "Andheri East",
        category: "commercial",
        x: 48,
        y: 22,
        level: 66,
        sensor: false,
        description: "MIDC Andheri & airport-adjacent logistics zone",
      },
      {
        id: "m5",
        name: "Marine Drive",
        category: "landmark",
        x: 28,
        y: 72,
        level: 38,
        sensor: false,
        description: "Sea-facing promenade; coastal breeze dilutes pollutants",
      },
      {
        id: "m6",
        name: "Bandra West",
        category: "residential",
        x: 36,
        y: 46,
        level: 48,
        sensor: false,
        description: "Upmarket residential suburb; moderate vehicle load",
      },
      {
        id: "m7",
        name: "Malad MIDC",
        category: "industrial",
        x: 42,
        y: 12,
        level: 76,
        sensor: true,
        description: "MIDC Malad West; plastic & pharmaceutical units",
      },
      {
        id: "m8",
        name: "Powai Lake",
        category: "water",
        x: 66,
        y: 26,
        level: 20,
        sensor: true,
        description: "Freshwater lake within city; IIT Bombay adjacent",
      },
      {
        id: "m9",
        name: "Kurla West",
        category: "residential",
        x: 58,
        y: 46,
        level: 68,
        sensor: false,
        description: "High-density residential; LBS Marg arterial road",
      },
    ],
  },

  // ── DELHI ─────────────────────────────────────────────────────────────────
  delhi: {
    cityId: "delhi",
    center: { lat: 28.6139, lng: 77.209 },
    zoom: 11,
    waterBodies: [
      { id: "dw1", name: "Yamuna River", x: 64, y: 38 },
      { id: "dw2", name: "Bhalswa Lake", x: 32, y: 18 },
      { id: "dw3", name: "Hauz Khas Lake", x: 40, y: 66 },
    ],
    zones: { residential: 54, industrial: 22, commercial: 18, greenCover: 6 },
    hotspots: [
      {
        id: "d1",
        name: "Anand Vihar",
        category: "industrial",
        x: 74,
        y: 28,
        level: 100,
        sensor: true,
        description: "ISBT bus terminus + Noida DTC gateway; worst AQI node in NCR",
      },
      {
        id: "d2",
        name: "ITO",
        category: "commercial",
        x: 50,
        y: 44,
        level: 88,
        sensor: true,
        description: "Government & media hub; Bahadur Shah Zafar Marg traffic",
      },
      {
        id: "d3",
        name: "Rohini",
        category: "residential",
        x: 26,
        y: 18,
        level: 72,
        sensor: false,
        description: "Planned satellite township; moderate pollution exposure",
      },
      {
        id: "d4",
        name: "Connaught Place",
        category: "commercial",
        x: 46,
        y: 46,
        level: 82,
        sensor: true,
        description: "CBD; pedestrianised inner circle with high ambient NO₂",
      },
      {
        id: "d5",
        name: "Yamuna Bank",
        category: "water",
        x: 64,
        y: 40,
        level: 20,
        sensor: true,
        description: "Yamuna flood-plain monitoring station; seasonal foam events",
      },
      {
        id: "d6",
        name: "Wazirpur",
        category: "industrial",
        x: 32,
        y: 28,
        level: 96,
        sensor: true,
        description: "Steel re-rolling mills; one of Delhi's known PM₂.₅ hotspots",
      },
      {
        id: "d7",
        name: "Okhla Phase II",
        category: "industrial",
        x: 58,
        y: 74,
        level: 92,
        sensor: true,
        description: "Printing & textile export zone; industrial waste corridor",
      },
      {
        id: "d8",
        name: "Lodhi Garden",
        category: "park",
        x: 44,
        y: 62,
        level: 36,
        sensor: false,
        description: "120-acre heritage park; greenest monitored node in central Delhi",
      },
      {
        id: "d9",
        name: "Dwarka",
        category: "residential",
        x: 18,
        y: 64,
        level: 68,
        sensor: false,
        description: "Sub-city residential zone; relatively lower industrial load",
      },
    ],
  },

  // ── HYDERABAD ─────────────────────────────────────────────────────────────
  hyderabad: {
    cityId: "hyderabad",
    center: { lat: 17.385, lng: 78.4867 },
    zoom: 12,
    waterBodies: [
      { id: "hw1", name: "Hussain Sagar", x: 42, y: 40 },
      { id: "hw2", name: "Osman Sagar", x: 16, y: 58 },
      { id: "hw3", name: "Himayat Sagar", x: 22, y: 72 },
    ],
    zones: { residential: 50, industrial: 20, commercial: 22, greenCover: 8 },
    hotspots: [
      {
        id: "h1",
        name: "HITEC City",
        category: "commercial",
        x: 30,
        y: 34,
        level: 58,
        sensor: true,
        description: "IT & ITES hub; high-density commuter load on Outer Ring Road",
      },
      {
        id: "h2",
        name: "Patancheru GIDC",
        category: "industrial",
        x: 16,
        y: 22,
        level: 88,
        sensor: true,
        description: "Bulk-drug & chemical GIDC; high VOC and SO₂ emissions",
      },
      {
        id: "h3",
        name: "Nampally",
        category: "commercial",
        x: 46,
        y: 52,
        level: 62,
        sensor: false,
        description: "Central Railway Station area; high mixed-traffic density",
      },
      {
        id: "h4",
        name: "Hussain Sagar",
        category: "water",
        x: 44,
        y: 42,
        level: 18,
        sensor: true,
        description: "16th-century urban lake; sediment & algal bloom monitoring",
      },
      {
        id: "h5",
        name: "Secunderabad",
        category: "commercial",
        x: 54,
        y: 36,
        level: 62,
        sensor: false,
        description: "Twin-city commercial hub; Cantonment & rail junction node",
      },
      {
        id: "h6",
        name: "Jeedimetla",
        category: "industrial",
        x: 28,
        y: 24,
        level: 82,
        sensor: true,
        description: "Pharmaceutical clusters; particulate & solvent emissions",
      },
      {
        id: "h7",
        name: "Golconda Fort",
        category: "landmark",
        x: 22,
        y: 60,
        level: 34,
        sensor: false,
        description: "16th-century Qutb Shahi fort; heritage green buffer",
      },
      {
        id: "h8",
        name: "LB Nagar",
        category: "residential",
        x: 64,
        y: 72,
        level: 50,
        sensor: false,
        description: "Eastern residential growth corridor; highway proximity",
      },
    ],
  },

  // ── CHENNAI ───────────────────────────────────────────────────────────────
  chennai: {
    cityId: "chennai",
    center: { lat: 13.0827, lng: 80.2707 },
    zoom: 12,
    waterBodies: [
      { id: "cnw1", name: "Adyar River", x: 50, y: 76 },
      { id: "cnw2", name: "Pallikaranai Marsh", x: 60, y: 84 },
      { id: "cnw3", name: "Cooum River", x: 36, y: 48 },
    ],
    zones: { residential: 56, industrial: 16, commercial: 20, greenCover: 8 },
    hotspots: [
      {
        id: "cn1",
        name: "Ambattur Industrial Estate",
        category: "industrial",
        x: 22,
        y: 26,
        level: 82,
        sensor: true,
        description: "State's largest SIDCO estate; auto-parts & electronics manufacturing",
      },
      {
        id: "cn2",
        name: "Marina Beach",
        category: "landmark",
        x: 70,
        y: 56,
        level: 28,
        sensor: false,
        description: "World's second-longest urban beach; sea breeze ventilation",
      },
      {
        id: "cn3",
        name: "T Nagar",
        category: "commercial",
        x: 48,
        y: 60,
        level: 64,
        sensor: true,
        description: "Densest retail district in Asia; extreme pedestrian & vehicle load",
      },
      {
        id: "cn4",
        name: "Manali Industrial Zone",
        category: "industrial",
        x: 44,
        y: 16,
        level: 88,
        sensor: true,
        description: "Oil refinery & fertiliser complex; SO₂ & PM₂.₅ critical zone",
      },
      {
        id: "cn5",
        name: "Adyar",
        category: "residential",
        x: 54,
        y: 78,
        level: 42,
        sensor: false,
        description: "Southern residential suburb; Adyar River estuary zone",
      },
      {
        id: "cn6",
        name: "Koyambedu",
        category: "commercial",
        x: 34,
        y: 40,
        level: 68,
        sensor: true,
        description: "Wholesale market hub; heavy goods vehicle concentration",
      },
      {
        id: "cn7",
        name: "Pallikaranai Marsh",
        category: "water",
        x: 60,
        y: 86,
        level: 14,
        sensor: true,
        description: "Protected freshwater wetland; biodiversity monitoring station",
      },
      {
        id: "cn8",
        name: "Anna Nagar",
        category: "residential",
        x: 36,
        y: 36,
        level: 48,
        sensor: false,
        description: "Planned residential layout; above-average green cover",
      },
    ],
  },

  // ── PUNE ──────────────────────────────────────────────────────────────────
  pune: {
    cityId: "pune",
    center: { lat: 18.5204, lng: 73.8567 },
    zoom: 12,
    waterBodies: [
      { id: "pw1", name: "Mula River", x: 38, y: 36 },
      { id: "pw2", name: "Mutha River", x: 44, y: 54 },
      { id: "pw3", name: "Pashan Lake", x: 20, y: 44 },
    ],
    zones: { residential: 52, industrial: 22, commercial: 18, greenCover: 8 },
    hotspots: [
      {
        id: "p1",
        name: "Pimpri-Chinchwad",
        category: "industrial",
        x: 22,
        y: 22,
        level: 80,
        sensor: true,
        description: "Auto-industrial hub; Tata & Bajaj plants; PM₁₀ critical node",
      },
      {
        id: "p2",
        name: "Hinjewadi",
        category: "commercial",
        x: 16,
        y: 38,
        level: 52,
        sensor: true,
        description: "Rajiv Gandhi Infotech Park Phase I–III; rising commuter load",
      },
      {
        id: "p3",
        name: "FC Road",
        category: "commercial",
        x: 44,
        y: 46,
        level: 58,
        sensor: false,
        description: "Fergusson College Road; busy F&B & retail artery",
      },
      {
        id: "p4",
        name: "Bhosari MIDC",
        category: "industrial",
        x: 34,
        y: 20,
        level: 76,
        sensor: true,
        description: "MIDC estate; defence & aerospace manufacturing cluster",
      },
      {
        id: "p5",
        name: "Mula River Bank",
        category: "water",
        x: 40,
        y: 36,
        level: 18,
        sensor: true,
        description: "Mula river confluence point; effluent-discharge monitoring site",
      },
      {
        id: "p6",
        name: "Koregaon Park",
        category: "residential",
        x: 58,
        y: 44,
        level: 46,
        sensor: false,
        description: "Upscale residential & hospitality zone; OSHO ashram precinct",
      },
      {
        id: "p7",
        name: "Sinhagad Fort",
        category: "landmark",
        x: 24,
        y: 80,
        level: 22,
        sensor: false,
        description: "Sahyadri hill fort; cleanest AQI node in the Pune region",
      },
      {
        id: "p8",
        name: "Kothrud",
        category: "residential",
        x: 30,
        y: 58,
        level: 48,
        sensor: false,
        description: "Large planned residential area; moderate industrial proximity",
      },
      {
        id: "p9",
        name: "Hadapsar",
        category: "industrial",
        x: 68,
        y: 58,
        level: 70,
        sensor: true,
        description: "Magarpatta & Fursungi; fast-growing industrial-residential mix",
      },
    ],
  },

  // ── KOLKATA ───────────────────────────────────────────────────────────────
  kolkata: {
    cityId: "kolkata",
    center: { lat: 22.5726, lng: 88.3639 },
    zoom: 12,
    waterBodies: [
      { id: "kw1", name: "Hooghly River", x: 28, y: 42 },
      { id: "kw2", name: "East Calcutta Wetlands", x: 72, y: 58 },
    ],
    zones: { residential: 58, industrial: 20, commercial: 16, greenCover: 6 },
    hotspots: [
      {
        id: "k1",
        name: "Howrah Bridge",
        category: "landmark",
        x: 36,
        y: 40,
        level: 68,
        sensor: true,
        description: "Iconic cantilever bridge; ambient NO₂ and PM hotspot",
      },
      {
        id: "k2",
        name: "Tangra",
        category: "industrial",
        x: 66,
        y: 52,
        level: 84,
        sensor: true,
        description: "Leather tannery cluster; chromium & effluent monitoring site",
      },
      {
        id: "k3",
        name: "Park Street",
        category: "commercial",
        x: 46,
        y: 56,
        level: 58,
        sensor: false,
        description: "Cultural & F&B avenue; moderate vehicle density",
      },
      {
        id: "k4",
        name: "Hooghly River",
        category: "water",
        x: 28,
        y: 38,
        level: 18,
        sensor: true,
        description: "Ganges distributary; industrial effluent entry point monitoring",
      },
      {
        id: "k5",
        name: "Salt Lake City",
        category: "commercial",
        x: 70,
        y: 26,
        level: 52,
        sensor: false,
        description: "IT Sector V & Sector III; low industrial, higher vehicular load",
      },
      {
        id: "k6",
        name: "Maidan",
        category: "park",
        x: 42,
        y: 52,
        level: 28,
        sensor: false,
        description: "1,000-acre lungs of Kolkata; lowest AQI in the metropolitan area",
      },
      {
        id: "k7",
        name: "Garden Reach",
        category: "industrial",
        x: 28,
        y: 72,
        level: 88,
        sensor: true,
        description: "Shipyard & engineering works; riverside heavy-industry corridor",
      },
      {
        id: "k8",
        name: "New Town",
        category: "commercial",
        x: 76,
        y: 20,
        level: 48,
        sensor: false,
        description: "Planned smart-city extension; lower density & better green cover",
      },
    ],
  },

  // ── LONDON ────────────────────────────────────────────────────────────────
  london: {
    cityId: "london",
    center: { lat: 51.5074, lng: -0.1278 },
    zoom: 11,
    waterBodies: [
      { id: "lw1", name: "River Thames", x: 44, y: 58 },
      { id: "lw2", name: "Regent's Canal", x: 38, y: 34 },
      { id: "lw3", name: "Serpentine Lake", x: 36, y: 52 },
    ],
    zones: { residential: 58, industrial: 12, commercial: 22, greenCover: 8 },
    hotspots: [
      {
        id: "l1",
        name: "City of London",
        category: "commercial",
        x: 54,
        y: 42,
        level: 44,
        sensor: true,
        description: "Square Mile; below average but NO₂ still elevated at street-level",
      },
      {
        id: "l2",
        name: "Canary Wharf",
        category: "commercial",
        x: 66,
        y: 44,
        level: 36,
        sensor: true,
        description: "Docklands financial hub; excellent ULEZ compliance",
      },
      {
        id: "l3",
        name: "Heathrow Airport",
        category: "industrial",
        x: 16,
        y: 58,
        level: 62,
        sensor: true,
        description: "Busiest airport in Europe; UK's single largest NO₂ source",
      },
      {
        id: "l4",
        name: "Camden",
        category: "residential",
        x: 44,
        y: 26,
        level: 38,
        sensor: false,
        description: "Inner-city residential & arts district; moderate traffic load",
      },
      {
        id: "l5",
        name: "Battersea",
        category: "residential",
        x: 42,
        y: 60,
        level: 32,
        sensor: false,
        description: "South-bank residential; Battersea Power Station regeneration",
      },
      {
        id: "l6",
        name: "River Thames Bank",
        category: "water",
        x: 48,
        y: 58,
        level: 14,
        sensor: true,
        description: "Tidal Thames; continuous water-quality monitoring network",
      },
      {
        id: "l7",
        name: "Queen Elizabeth Park",
        category: "park",
        x: 68,
        y: 28,
        level: 18,
        sensor: false,
        description: "2012 Olympic legacy park; greened brownfield site",
      },
      {
        id: "l8",
        name: "Southall",
        category: "residential",
        x: 20,
        y: 52,
        level: 48,
        sensor: false,
        description: "West London suburb; elevated PM from M4/M25 proximity",
      },
    ],
  },

  // ── NEW YORK ──────────────────────────────────────────────────────────────
  newyork: {
    cityId: "newyork",
    center: { lat: 40.7128, lng: -74.006 },
    zoom: 11,
    waterBodies: [
      { id: "nyw1", name: "Hudson River", x: 30, y: 50 },
      { id: "nyw2", name: "East River", x: 58, y: 44 },
      { id: "nyw3", name: "Jamaica Bay", x: 72, y: 70 },
    ],
    zones: { residential: 52, industrial: 16, commercial: 24, greenCover: 8 },
    hotspots: [
      {
        id: "ny1",
        name: "Midtown Manhattan",
        category: "commercial",
        x: 48,
        y: 34,
        level: 56,
        sensor: true,
        description: "Times Square & Grand Central; pedestrian canyon with trapped PM",
      },
      {
        id: "ny2",
        name: "South Bronx",
        category: "industrial",
        x: 54,
        y: 20,
        level: 74,
        sensor: true,
        description: "Environmental justice hotspot; waste transfer & expressway PM",
      },
      {
        id: "ny3",
        name: "Red Hook, Brooklyn",
        category: "industrial",
        x: 44,
        y: 60,
        level: 68,
        sensor: true,
        description: "Port container terminal & industrial waterfront zone",
      },
      {
        id: "ny4",
        name: "Staten Island North",
        category: "residential",
        x: 28,
        y: 72,
        level: 36,
        sensor: false,
        description: "Residential borough; lowest PM₂.₅ among the five boroughs",
      },
      {
        id: "ny5",
        name: "Hudson River Waterfront",
        category: "water",
        x: 32,
        y: 50,
        level: 16,
        sensor: true,
        description: "Estuarine ecosystem; EPA Superfund legacy site monitoring",
      },
      {
        id: "ny6",
        name: "Central Park",
        category: "park",
        x: 46,
        y: 26,
        level: 20,
        sensor: false,
        description: "843-acre urban lung; consistently lowest AQI in Manhattan",
      },
      {
        id: "ny7",
        name: "JFK Airport Zone",
        category: "industrial",
        x: 74,
        y: 66,
        level: 70,
        sensor: true,
        description: "International airport & cargo hub; ultrafine particle corridor",
      },
      {
        id: "ny8",
        name: "Flushing, Queens",
        category: "commercial",
        x: 68,
        y: 36,
        level: 52,
        sensor: false,
        description: "Dense commercial-residential mix; 7 subway line node",
      },
    ],
  },

  // ── SINGAPORE ─────────────────────────────────────────────────────────────
  singapore: {
    cityId: "singapore",
    center: { lat: 1.3521, lng: 103.8198 },
    zoom: 12,
    waterBodies: [
      { id: "sgw1", name: "MacRitchie Reservoir", x: 44, y: 26 },
      { id: "sgw2", name: "Marina Reservoir", x: 58, y: 56 },
      { id: "sgw3", name: "Kallang River", x: 52, y: 40 },
    ],
    zones: { residential: 46, industrial: 22, commercial: 20, greenCover: 12 },
    hotspots: [
      {
        id: "sg1",
        name: "Jurong Island",
        category: "industrial",
        x: 16,
        y: 66,
        level: 72,
        sensor: true,
        description: "Petrochemical & refinery complex; Singapore's largest industrial zone",
      },
      {
        id: "sg2",
        name: "Marina Bay",
        category: "commercial",
        x: 58,
        y: 54,
        level: 38,
        sensor: true,
        description: "CBD & Gardens by the Bay; well-ventilated coastal site",
      },
      {
        id: "sg3",
        name: "Buona Vista",
        category: "commercial",
        x: 34,
        y: 46,
        level: 40,
        sensor: false,
        description: "one-north R&D park; Biopolis & Fusionopolis precinct",
      },
      {
        id: "sg4",
        name: "Changi Airport",
        category: "industrial",
        x: 84,
        y: 36,
        level: 62,
        sensor: true,
        description: "World's most awarded airport; aviation emissions monitoring zone",
      },
      {
        id: "sg5",
        name: "MacRitchie Reservoir",
        category: "water",
        x: 44,
        y: 26,
        level: 10,
        sensor: true,
        description: "Central Catchment Nature Reserve; cleanest air node on the island",
      },
      {
        id: "sg6",
        name: "Sentosa Island",
        category: "landmark",
        x: 48,
        y: 76,
        level: 22,
        sensor: false,
        description: "Resort island; sea-breeze dispersion advantage",
      },
      {
        id: "sg7",
        name: "Woodlands",
        category: "residential",
        x: 34,
        y: 14,
        level: 34,
        sensor: false,
        description: "Northern HDB new town; Johor Strait waterfront",
      },
      {
        id: "sg8",
        name: "Tuas West",
        category: "industrial",
        x: 10,
        y: 48,
        level: 66,
        sensor: true,
        description: "Second-phase industrial expansion; port & logistics corridor",
      },
    ],
  },

  // ── TOKYO ─────────────────────────────────────────────────────────────────
  tokyo: {
    cityId: "tokyo",
    center: { lat: 35.6762, lng: 139.6503 },
    zoom: 11,
    waterBodies: [
      { id: "tw1", name: "Sumida River", x: 58, y: 36 },
      { id: "tw2", name: "Tokyo Bay", x: 58, y: 68 },
      { id: "tw3", name: "Tama River", x: 18, y: 64 },
    ],
    zones: { residential: 54, industrial: 18, commercial: 24, greenCover: 4 },
    hotspots: [
      {
        id: "t1",
        name: "Shinjuku",
        category: "commercial",
        x: 38,
        y: 40,
        level: 60,
        sensor: true,
        description: "Densest commercial hub in Japan; car & rail interchange",
      },
      {
        id: "t2",
        name: "Shibuya",
        category: "commercial",
        x: 40,
        y: 56,
        level: 56,
        sensor: false,
        description: "Major shopping & entertainment crossroads; PM₂.₅ benchmark site",
      },
      {
        id: "t3",
        name: "Koto Ward",
        category: "industrial",
        x: 68,
        y: 44,
        level: 74,
        sensor: true,
        description: "Eastern industrial waterfront; historically highest NOx in Tokyo",
      },
      {
        id: "t4",
        name: "Sumida River",
        category: "water",
        x: 58,
        y: 32,
        level: 18,
        sensor: true,
        description: "Urban river; continuous water & air quality monitoring network",
      },
      {
        id: "t5",
        name: "Asakusa",
        category: "landmark",
        x: 56,
        y: 28,
        level: 40,
        sensor: false,
        description: "Senso-ji temple district; heritage tourism & traditional crafts",
      },
      {
        id: "t6",
        name: "Shinagawa",
        category: "commercial",
        x: 46,
        y: 68,
        level: 52,
        sensor: false,
        description: "Shinkansen gateway; large-scale office & hotel cluster",
      },
      {
        id: "t7",
        name: "Chiba Coastal",
        category: "industrial",
        x: 82,
        y: 58,
        level: 78,
        sensor: true,
        description: "Chiba steel & petrochemical corridor; JX Nippon refinery",
      },
      {
        id: "t8",
        name: "Odaiba",
        category: "commercial",
        x: 56,
        y: 62,
        level: 44,
        sensor: false,
        description: "Artificial island; open-air retail & exhibition zone",
      },
    ],
  },

  // ── DUBAI ─────────────────────────────────────────────────────────────────
  dubai: {
    cityId: "dubai",
    center: { lat: 25.2048, lng: 55.2708 },
    zoom: 12,
    waterBodies: [
      { id: "dbw1", name: "Dubai Creek", x: 52, y: 36 },
      { id: "dbw2", name: "Arabian Gulf Coastline", x: 26, y: 64 },
      { id: "dbw3", name: "Palm Jumeirah Lagoon", x: 24, y: 56 },
    ],
    zones: { residential: 38, industrial: 28, commercial: 28, greenCover: 6 },
    hotspots: [
      {
        id: "db1",
        name: "Jebel Ali Port & JAFZA",
        category: "industrial",
        x: 10,
        y: 58,
        level: 88,
        sensor: true,
        description: "World's 9th busiest port + JAFZA free zone; highest marine PM in UAE",
      },
      {
        id: "db2",
        name: "Downtown Dubai",
        category: "commercial",
        x: 48,
        y: 50,
        level: 58,
        sensor: true,
        description: "Burj Khalifa district; high-rise canyon effect on pollutants",
      },
      {
        id: "db3",
        name: "Dubai Marina",
        category: "commercial",
        x: 26,
        y: 62,
        level: 52,
        sensor: false,
        description: "Waterfront residential & dining zone; sea breeze advantage",
      },
      {
        id: "db4",
        name: "Sharjah Industrial",
        category: "industrial",
        x: 80,
        y: 22,
        level: 84,
        sensor: true,
        description: "UAE–Sharjah industrial belt; cement & metal works cluster",
      },
      {
        id: "db5",
        name: "Dubai Creek",
        category: "water",
        x: 54,
        y: 34,
        level: 18,
        sensor: true,
        description: "Historic tidal inlet; sediment and salinity monitoring point",
      },
      {
        id: "db6",
        name: "Business Bay",
        category: "commercial",
        x: 52,
        y: 54,
        level: 62,
        sensor: false,
        description: "High-rise CBD; construction phase emissions still elevated",
      },
      {
        id: "db7",
        name: "Al Quoz Industrial",
        category: "industrial",
        x: 36,
        y: 64,
        level: 80,
        sensor: true,
        description: "Mid-city industrial zone; car workshops, paint shops & warehouses",
      },
      {
        id: "db8",
        name: "Dubai International Airport",
        category: "industrial",
        x: 60,
        y: 30,
        level: 76,
        sensor: true,
        description: "World's busiest international airport; aviation emission corridor",
      },
    ],
  },
};
