/**
 * mapLocations.seed.ts
 *
 * Seeds MapLocation and CityMapConfig collections for all 14 GreenGuard cities.
 *
 * Run standalone:
 *   ts-node -r tsconfig-paths/register src/seed/mapLocations.seed.ts
 *
 * Or call seedMapData() from your main seed/index.ts.
 *
 * To add a NEW city: append one entry to CITY_MAP_SEED below.
 * No controller changes are ever required.
 */

import mongoose from "mongoose";
import { MapLocation, LocationCategory, SensorType } from "../models/MapLocation";
import { CityMapConfig } from "../models/CityMapConfig";

// ─── Types ────────────────────────────────────────────────────────────────────
interface LocationSeed {
  locationId: string;
  name: string;
  category: LocationCategory;
  latitude: number;
  longitude: number;
  mapX: number;
  mapY: number;
  pollutionMultiplier: number;
  sensorAvailable: boolean;
  /**
   * Optional explicit override. When omitted, sensorType is derived
   * deterministically from `category` + `sensorAvailable` by
   * deriveSensorType() below — see that function for the mapping rule.
   */
  sensorType?: SensorType;
  description: string;
}

interface WaterBodySeed {
  id: string;
  name: string;
  /** Legacy SVG canvas position (0–100%). Retained for the drawer list. */
  x: number;
  y: number;
  /** Real-world coordinates (Phase 1 GIS upgrade) — required for map rendering. */
  latitude: number;
  longitude: number;
}

interface ZonesSeed {
  residential: number;
  industrial: number;
  commercial: number;
  greenCover: number;
}

interface CitySeed {
  cityId: string;
  center: { lat: number; lng: number };
  zoom: number;
  /** Optional camera bearing in degrees. Defaults to 0 (north-up) when omitted. */
  bearing?: number;
  /** Optional camera pitch/tilt in degrees. Defaults to 0 (top-down) when omitted. */
  pitch?: number;
  waterBodies: WaterBodySeed[];
  zones: ZonesSeed;
  locations: LocationSeed[];
}

// ─── Seed data: all 14 cities ─────────────────────────────────────────────────
export const CITY_MAP_SEED: CitySeed[] = [
  // ──────────────────────────────────────────────────────────────────────────
  //  AHMEDABAD  (lat 23.02, lng 72.57)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "ahmedabad",
    center: { lat: 23.0225, lng: 72.5714 },
    zoom: 12,
    waterBodies: [
      { id: "aw1", name: "Sabarmati River", x: 42, y: 38, latitude: 23.034, longitude: 72.5773 },
      { id: "aw2", name: "Kankaria Lake", x: 62, y: 72, latitude: 22.9883, longitude: 72.6063 },
      { id: "aw3", name: "Chandola Lake", x: 70, y: 80, latitude: 22.963, longitude: 72.621 },
    ],
    zones: { residential: 52, industrial: 22, commercial: 18, greenCover: 8 },
    locations: [
      {
        locationId: "a1",
        name: "Naroda GIDC",
        category: "industrial",
        latitude: 23.0703,
        longitude: 72.6467,
        mapX: 72,
        mapY: 28,
        pollutionMultiplier: 1.45,
        sensorAvailable: true,
        description: "Largest GIDC estate; heavy chemicals, dyes & textiles",
      },
      {
        locationId: "a2",
        name: "Vatva GIDC",
        category: "industrial",
        latitude: 22.9769,
        longitude: 72.6401,
        mapX: 78,
        mapY: 64,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "Chemical & pharmaceutical industrial cluster",
      },
      {
        locationId: "a3",
        name: "Sabarmati Riverfront",
        category: "water",
        latitude: 23.034,
        longitude: 72.5773,
        mapX: 44,
        mapY: 40,
        pollutionMultiplier: 0.35,
        sensorAvailable: true,
        description: "Revamped riverfront promenade; water quality monitoring station",
      },
      {
        locationId: "a4",
        name: "CG Road",
        category: "commercial",
        latitude: 23.022,
        longitude: 72.557,
        mapX: 46,
        mapY: 48,
        pollutionMultiplier: 1.05,
        sensorAvailable: true,
        description: "Dense commercial corridor with high vehicle load",
      },
      {
        locationId: "a5",
        name: "Satellite",
        category: "residential",
        latitude: 23.0151,
        longitude: 72.5157,
        mapX: 34,
        mapY: 58,
        pollutionMultiplier: 0.78,
        sensorAvailable: false,
        description: "Upmarket residential township; moderate pollution exposure",
      },
      {
        locationId: "a6",
        name: "Prahlad Nagar",
        category: "commercial",
        latitude: 23.0019,
        longitude: 72.5077,
        mapX: 40,
        mapY: 68,
        pollutionMultiplier: 0.92,
        sensorAvailable: true,
        description: "IT & retail hub; SEZ-adjacent traffic congestion",
      },
      {
        locationId: "a7",
        name: "Kankaria Lake",
        category: "water",
        latitude: 22.9883,
        longitude: 72.6063,
        mapX: 62,
        mapY: 72,
        pollutionMultiplier: 0.28,
        sensorAvailable: true,
        description: "Historic 15th-century lake; ongoing water quality restoration",
      },
      {
        locationId: "a8",
        name: "Odhav Industrial",
        category: "industrial",
        latitude: 23.0038,
        longitude: 72.6488,
        mapX: 82,
        mapY: 60,
        pollutionMultiplier: 1.3,
        sensorAvailable: false,
        description: "Auto-parts & plastics manufacturing zone",
      },
      {
        locationId: "a9",
        name: "Maninagar",
        category: "residential",
        latitude: 22.999,
        longitude: 72.6056,
        mapX: 60,
        mapY: 62,
        pollutionMultiplier: 0.85,
        sensorAvailable: false,
        description: "Dense residential area between two GIDCs",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  BELAGAVI  (lat 15.85, lng 74.50)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "belagavi",
    center: { lat: 15.8497, lng: 74.4977 },
    zoom: 13,
    waterBodies: [
      { id: "bw1", name: "Rakaskop Reservoir", x: 62, y: 70, latitude: 15.748, longitude: 74.419 },
      { id: "bw2", name: "Markandeya River", x: 24, y: 62, latitude: 15.821, longitude: 74.461 },
      {
        id: "bw3",
        name: "Fort Lake (Kote Kere)",
        x: 54,
        y: 40,
        latitude: 15.8605,
        longitude: 74.5045,
      },
    ],
    zones: { residential: 55, industrial: 18, commercial: 15, greenCover: 12 },
    // Phase 4 spatial audit (against OpenStreetMap / Wikipedia / civic sources):
    // b1–b8 were reviewed and left unchanged — coordinates are plausible for
    // their named real places. b9–b16 are new, each an individually verified
    // real Belagavi landmark (see per-row description for the source context).
    // b16 (APMC Yard) is flagged lower-confidence — locality-level precision
    // only, not a verified point address; noted rather than guessed further.
    locations: [
      {
        locationId: "b1",
        name: "Tilakwadi",
        category: "residential",
        latitude: 15.849,
        longitude: 74.488,
        mapX: 36,
        mapY: 44,
        pollutionMultiplier: 0.82,
        sensorAvailable: false,
        description: "Central residential neighbourhood; mixed-use traffic hub",
      },
      {
        locationId: "b2",
        name: "Shahapur",
        category: "residential",
        latitude: 15.8608,
        longitude: 74.509,
        mapX: 54,
        mapY: 38,
        pollutionMultiplier: 0.76,
        sensorAvailable: false,
        description: "Old city residential quarter; traditional housing fabric",
      },
      {
        locationId: "b3",
        name: "Udyambag",
        category: "industrial",
        latitude: 15.838,
        longitude: 74.531,
        mapX: 68,
        mapY: 52,
        pollutionMultiplier: 1.28,
        sensorAvailable: true,
        description: "Mixed-use industrial estate; foundry & light engineering",
      },
      {
        locationId: "b4",
        name: "Machhe Industrial Area",
        category: "industrial",
        latitude: 15.873,
        longitude: 74.548,
        mapX: 78,
        mapY: 28,
        pollutionMultiplier: 1.4,
        sensorAvailable: true,
        description: "Karnataka SIDCO industrial area; textiles & chemicals",
      },
      {
        locationId: "b5",
        name: "Belagavi Fort",
        category: "landmark",
        latitude: 15.8614,
        longitude: 74.5036,
        mapX: 46,
        mapY: 28,
        pollutionMultiplier: 0.6,
        sensorAvailable: false,
        description: "16th-century Maratha fort; heritage conservation zone",
      },
      {
        locationId: "b6",
        name: "Rani Chennamma Circle",
        category: "commercial",
        latitude: 15.8502,
        longitude: 74.5001,
        mapX: 50,
        mapY: 46,
        pollutionMultiplier: 0.98,
        sensorAvailable: true,
        description: "City centre roundabout; high pedestrian & vehicle density",
      },
      {
        locationId: "b7",
        name: "Vaccine Depot Area",
        category: "commercial",
        latitude: 15.8432,
        longitude: 74.494,
        mapX: 42,
        mapY: 56,
        pollutionMultiplier: 0.88,
        sensorAvailable: false,
        description: "Healthcare & logistics commercial cluster",
      },
      {
        locationId: "b8",
        name: "Markandeya River Bank",
        category: "water",
        latitude: 15.821,
        longitude: 74.461,
        mapX: 22,
        mapY: 68,
        pollutionMultiplier: 0.32,
        sensorAvailable: true,
        description: "Seasonal river; upstream pollution monitoring point",
      },
      {
        locationId: "b9",
        name: "Belgavi KSRTC Central Bus Stand",
        category: "commercial",
        latitude: 15.8614,
        longitude: 74.5204,
        mapX: 63,
        mapY: 40,
        pollutionMultiplier: 1.08,
        sensorAvailable: true,
        description:
          "Principal interstate KSRTC bus terminal; sustained diesel-bus idling and vehicle congestion",
      },
      {
        locationId: "b10",
        name: "Belagavi Railway Station",
        category: "commercial",
        latitude: 15.8501,
        longitude: 74.5084,
        mapX: 56,
        mapY: 50,
        pollutionMultiplier: 1.02,
        sensorAvailable: true,
        description:
          "South Western Railway's Belagavi terminus (station code BGM); passenger and freight transit corridor",
      },
      {
        locationId: "b11",
        name: "Suvarna Vidhana Soudha",
        category: "landmark",
        latitude: 15.8144,
        longitude: 74.5704,
        mapX: 92,
        mapY: 82,
        pollutionMultiplier: 0.55,
        sensorAvailable: true,
        description:
          "Karnataka's second legislature building; landscaped 127-acre government campus off the Bengaluru–Mumbai highway (Halga-Bastwad)",
      },
      {
        locationId: "b12",
        name: "KLE Hospital (JNMC Campus)",
        category: "landmark",
        latitude: 15.8667,
        longitude: 74.4999,
        mapX: 51,
        mapY: 35,
        pollutionMultiplier: 0.8,
        sensorAvailable: true,
        description:
          "KLE Society's Dr. Prabhakar Kore Hospital & JNMC campus, Nehru Nagar; major tertiary healthcare centre with heavy staff/visitor/ambulance traffic",
      },
      {
        locationId: "b13",
        name: "Fort Lake (Kote Kere)",
        category: "park",
        latitude: 15.8605,
        longitude: 74.5045,
        mapX: 54,
        mapY: 40,
        pollutionMultiplier: 0.38,
        sensorAvailable: true,
        description:
          "Public lake and garden beside Belagavi Fort; boating, walking paths and a large flag memorial",
      },
      {
        locationId: "b14",
        name: "Belagavi Cantonment (Camp)",
        category: "park",
        latitude: 15.858,
        longitude: 74.516,
        mapX: 60,
        mapY: 43,
        pollutionMultiplier: 0.45,
        sensorAvailable: false,
        description:
          "Historic Cantonment green belt around Church Road Garden; the city's largest tree canopy",
      },
      {
        locationId: "b15",
        name: "Belagavi Airport (Sambra)",
        category: "landmark",
        sensorType: "traffic",
        latitude: 15.8629,
        longitude: 74.6112,
        mapX: 98,
        mapY: 38,
        pollutionMultiplier: 0.95,
        sensorAvailable: true,
        description:
          "Belagavi Airport (Sambra), ~10 km east of the city centre; regional aviation hub",
      },
      {
        locationId: "b16",
        name: "APMC Yard",
        category: "commercial",
        latitude: 15.858,
        longitude: 74.487,
        mapX: 44,
        mapY: 43,
        pollutionMultiplier: 0.98,
        sensorAvailable: false,
        description:
          "Agricultural produce market yard, Sangameshwar Nagar area — locality-level position, flagged for field verification",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  BENGALURU  (lat 12.97, lng 77.59)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "bengaluru",
    center: { lat: 12.9716, lng: 77.5946 },
    zoom: 12,
    waterBodies: [
      { id: "bgw1", name: "Bellandur Lake", x: 70, y: 68, latitude: 12.9275, longitude: 77.6682 },
      { id: "bgw2", name: "Ulsoor Lake", x: 52, y: 42, latitude: 12.9815, longitude: 77.6205 },
      { id: "bgw3", name: "Varthur Lake", x: 80, y: 72, latitude: 12.9412, longitude: 77.7418 },
    ],
    zones: { residential: 48, industrial: 20, commercial: 24, greenCover: 8 },
    locations: [
      {
        locationId: "bg1",
        name: "Whitefield",
        category: "commercial",
        latitude: 12.9698,
        longitude: 77.7499,
        mapX: 80,
        mapY: 42,
        pollutionMultiplier: 1.1,
        sensorAvailable: true,
        description: "IT corridor & ITPL; heavy commuter traffic on Outer Ring Road",
      },
      {
        locationId: "bg2",
        name: "Electronic City",
        category: "industrial",
        latitude: 12.8399,
        longitude: 77.677,
        mapX: 64,
        mapY: 80,
        pollutionMultiplier: 1.25,
        sensorAvailable: true,
        description: "India's first planned IT export zone; high diesel generator load",
      },
      {
        locationId: "bg3",
        name: "Hebbal",
        category: "commercial",
        latitude: 13.0358,
        longitude: 77.5971,
        mapX: 38,
        mapY: 22,
        pollutionMultiplier: 1.0,
        sensorAvailable: true,
        description: "NH junction flyover node; peak-hour AQI spikes to 180+",
      },
      {
        locationId: "bg4",
        name: "Koramangala",
        category: "commercial",
        latitude: 12.9279,
        longitude: 77.6271,
        mapX: 56,
        mapY: 60,
        pollutionMultiplier: 0.92,
        sensorAvailable: false,
        description: "Start-up & F&B hub; medium traffic density",
      },
      {
        locationId: "bg5",
        name: "Peenya",
        category: "industrial",
        latitude: 13.0284,
        longitude: 77.5191,
        mapX: 24,
        mapY: 36,
        pollutionMultiplier: 1.42,
        sensorAvailable: true,
        description: "Largest industrial estate in south India; metals & engineering",
      },
      {
        locationId: "bg6",
        name: "MG Road",
        category: "commercial",
        latitude: 12.9757,
        longitude: 77.6066,
        mapX: 48,
        mapY: 46,
        pollutionMultiplier: 0.98,
        sensorAvailable: false,
        description: "CBD retail corridor; high foot-fall and congestion",
      },
      {
        locationId: "bg7",
        name: "Bellandur Lake",
        category: "water",
        latitude: 12.9275,
        longitude: 77.6682,
        mapX: 70,
        mapY: 68,
        pollutionMultiplier: 0.22,
        sensorAvailable: true,
        description: "Largest lake in Bengaluru; foam & fire incidents tracked",
      },
      {
        locationId: "bg8",
        name: "Marathahalli",
        category: "commercial",
        latitude: 12.9591,
        longitude: 77.7008,
        mapX: 74,
        mapY: 52,
        pollutionMultiplier: 1.05,
        sensorAvailable: false,
        description: "High-density retail & residential corridor",
      },
      {
        locationId: "bg9",
        name: "Yelahanka",
        category: "residential",
        latitude: 13.1007,
        longitude: 77.5963,
        mapX: 38,
        mapY: 14,
        pollutionMultiplier: 0.7,
        sensorAvailable: false,
        description: "Northern residential suburb; Air Force Station proximity",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  MUMBAI  (lat 19.07, lng 72.87)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "mumbai",
    center: { lat: 19.076, lng: 72.8777 },
    zoom: 12,
    waterBodies: [
      { id: "mw1", name: "Powai Lake", x: 66, y: 26, latitude: 19.1199, longitude: 72.9067 },
      { id: "mw2", name: "Mahim Bay", x: 26, y: 58, latitude: 19.04, longitude: 72.84 },
      { id: "mw3", name: "Mumbai Harbour", x: 58, y: 68, latitude: 18.9633, longitude: 72.85 },
    ],
    zones: { residential: 50, industrial: 20, commercial: 24, greenCover: 6 },
    locations: [
      {
        locationId: "m1",
        name: "Dharavi",
        category: "industrial",
        latitude: 19.042,
        longitude: 72.8537,
        mapX: 32,
        mapY: 52,
        pollutionMultiplier: 1.42,
        sensorAvailable: true,
        description: "Dense mixed-use area with leather & recycling industries",
      },
      {
        locationId: "m2",
        name: "Bandra-Kurla Complex",
        category: "commercial",
        latitude: 19.0648,
        longitude: 72.8651,
        mapX: 58,
        mapY: 40,
        pollutionMultiplier: 0.95,
        sensorAvailable: true,
        description: "Prime CBD; Bandra-Worli Sea Link traffic gateway",
      },
      {
        locationId: "m3",
        name: "Chembur",
        category: "industrial",
        latitude: 19.0623,
        longitude: 72.899,
        mapX: 72,
        mapY: 38,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "Refinery & petrochemical complex; legacy HPCL/BPCL emissions",
      },
      {
        locationId: "m4",
        name: "Andheri East",
        category: "commercial",
        latitude: 19.1136,
        longitude: 72.8696,
        mapX: 48,
        mapY: 22,
        pollutionMultiplier: 1.05,
        sensorAvailable: false,
        description: "MIDC Andheri & airport-adjacent logistics zone",
      },
      {
        locationId: "m5",
        name: "Marine Drive",
        category: "landmark",
        latitude: 18.9432,
        longitude: 72.8238,
        mapX: 28,
        mapY: 72,
        pollutionMultiplier: 0.62,
        sensorAvailable: false,
        description: "Sea-facing promenade; coastal breeze dilutes pollutants",
      },
      {
        locationId: "m6",
        name: "Bandra West",
        category: "residential",
        latitude: 19.0596,
        longitude: 72.8295,
        mapX: 36,
        mapY: 46,
        pollutionMultiplier: 0.78,
        sensorAvailable: false,
        description: "Upmarket residential suburb; moderate vehicle load",
      },
      {
        locationId: "m7",
        name: "Malad MIDC",
        category: "industrial",
        latitude: 19.1875,
        longitude: 72.8494,
        mapX: 42,
        mapY: 12,
        pollutionMultiplier: 1.22,
        sensorAvailable: true,
        description: "MIDC Malad West; plastic & pharmaceutical units",
      },
      {
        locationId: "m8",
        name: "Powai Lake",
        category: "water",
        latitude: 19.1199,
        longitude: 72.9067,
        mapX: 66,
        mapY: 26,
        pollutionMultiplier: 0.3,
        sensorAvailable: true,
        description: "Freshwater lake within city; IIT Bombay adjacent",
      },
      {
        locationId: "m9",
        name: "Kurla West",
        category: "residential",
        latitude: 19.0726,
        longitude: 72.8788,
        mapX: 58,
        mapY: 46,
        pollutionMultiplier: 1.12,
        sensorAvailable: false,
        description: "High-density residential; LBS Marg arterial road",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  DELHI  (lat 28.61, lng 77.21)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "delhi",
    center: { lat: 28.6139, lng: 77.209 },
    zoom: 11,
    waterBodies: [
      { id: "dw1", name: "Yamuna River", x: 64, y: 38, latitude: 28.635, longitude: 77.3009 },
      { id: "dw2", name: "Bhalswa Lake", x: 32, y: 18, latitude: 28.7472, longitude: 77.1642 },
      { id: "dw3", name: "Hauz Khas Lake", x: 40, y: 66, latitude: 28.5535, longitude: 77.2004 },
    ],
    zones: { residential: 54, industrial: 22, commercial: 18, greenCover: 6 },
    locations: [
      {
        locationId: "d1",
        name: "Anand Vihar",
        category: "industrial",
        latitude: 28.6469,
        longitude: 77.3155,
        mapX: 74,
        mapY: 28,
        pollutionMultiplier: 1.48,
        sensorAvailable: true,
        description: "ISBT bus terminus + Noida DTC gateway; worst AQI node in NCR",
      },
      {
        locationId: "d2",
        name: "ITO",
        category: "commercial",
        latitude: 28.6289,
        longitude: 77.2497,
        mapX: 50,
        mapY: 44,
        pollutionMultiplier: 1.18,
        sensorAvailable: true,
        description: "Government & media hub; Bahadur Shah Zafar Marg traffic",
      },
      {
        locationId: "d3",
        name: "Rohini",
        category: "residential",
        latitude: 28.7497,
        longitude: 77.066,
        mapX: 26,
        mapY: 18,
        pollutionMultiplier: 0.88,
        sensorAvailable: false,
        description: "Planned satellite township; moderate pollution exposure",
      },
      {
        locationId: "d4",
        name: "Connaught Place",
        category: "commercial",
        latitude: 28.6315,
        longitude: 77.2167,
        mapX: 46,
        mapY: 46,
        pollutionMultiplier: 1.08,
        sensorAvailable: true,
        description: "CBD; pedestrianised inner circle with high ambient NO₂",
      },
      {
        locationId: "d5",
        name: "Yamuna Bank",
        category: "water",
        latitude: 28.635,
        longitude: 77.3009,
        mapX: 64,
        mapY: 40,
        pollutionMultiplier: 0.25,
        sensorAvailable: true,
        description: "Yamuna flood-plain monitoring station; seasonal foam events",
      },
      {
        locationId: "d6",
        name: "Wazirpur",
        category: "industrial",
        latitude: 28.7036,
        longitude: 77.1693,
        mapX: 32,
        mapY: 28,
        pollutionMultiplier: 1.4,
        sensorAvailable: true,
        description: "Steel re-rolling mills; one of Delhi's known PM₂.₅ hotspots",
      },
      {
        locationId: "d7",
        name: "Okhla Phase II",
        category: "industrial",
        latitude: 28.5504,
        longitude: 77.2717,
        mapX: 58,
        mapY: 74,
        pollutionMultiplier: 1.35,
        sensorAvailable: true,
        description: "Printing & textile export zone; industrial waste corridor",
      },
      {
        locationId: "d8",
        name: "Lodhi Garden",
        category: "park",
        latitude: 28.5931,
        longitude: 77.2211,
        mapX: 44,
        mapY: 62,
        pollutionMultiplier: 0.42,
        sensorAvailable: false,
        description: "120-acre heritage park; greenest monitored node in central Delhi",
      },
      {
        locationId: "d9",
        name: "Dwarka",
        category: "residential",
        latitude: 28.5921,
        longitude: 77.046,
        mapX: 18,
        mapY: 64,
        pollutionMultiplier: 0.92,
        sensorAvailable: false,
        description: "Sub-city residential zone; relatively lower industrial load",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  HYDERABAD  (lat 17.38, lng 78.48)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "hyderabad",
    center: { lat: 17.385, lng: 78.4867 },
    zoom: 12,
    waterBodies: [
      { id: "hw1", name: "Hussain Sagar", x: 42, y: 40, latitude: 17.4199, longitude: 78.4734 },
      { id: "hw2", name: "Osman Sagar", x: 16, y: 58, latitude: 17.3667, longitude: 78.2833 },
      { id: "hw3", name: "Himayat Sagar", x: 22, y: 72, latitude: 17.3333, longitude: 78.3333 },
    ],
    zones: { residential: 50, industrial: 20, commercial: 22, greenCover: 8 },
    locations: [
      {
        locationId: "h1",
        name: "HITEC City",
        category: "commercial",
        latitude: 17.4435,
        longitude: 78.3772,
        mapX: 30,
        mapY: 34,
        pollutionMultiplier: 0.96,
        sensorAvailable: true,
        description: "IT & ITES hub; high-density commuter load on Outer Ring Road",
      },
      {
        locationId: "h2",
        name: "Patancheru GIDC",
        category: "industrial",
        latitude: 17.5233,
        longitude: 78.2656,
        mapX: 16,
        mapY: 22,
        pollutionMultiplier: 1.45,
        sensorAvailable: true,
        description: "Bulk-drug & chemical GIDC; high VOC and SO₂ emissions",
      },
      {
        locationId: "h3",
        name: "Nampally",
        category: "commercial",
        latitude: 17.3844,
        longitude: 78.4697,
        mapX: 46,
        mapY: 52,
        pollutionMultiplier: 1.0,
        sensorAvailable: false,
        description: "Central Railway Station area; high mixed-traffic density",
      },
      {
        locationId: "h4",
        name: "Hussain Sagar",
        category: "water",
        latitude: 17.4199,
        longitude: 78.4734,
        mapX: 44,
        mapY: 42,
        pollutionMultiplier: 0.26,
        sensorAvailable: true,
        description: "16th-century urban lake; sediment & algal bloom monitoring",
      },
      {
        locationId: "h5",
        name: "Secunderabad",
        category: "commercial",
        latitude: 17.4399,
        longitude: 78.4983,
        mapX: 54,
        mapY: 36,
        pollutionMultiplier: 1.02,
        sensorAvailable: false,
        description: "Twin-city commercial hub; Cantonment & rail junction node",
      },
      {
        locationId: "h6",
        name: "Jeedimetla",
        category: "industrial",
        latitude: 17.4887,
        longitude: 78.4078,
        mapX: 28,
        mapY: 24,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "Pharmaceutical clusters; particulate & solvent emissions",
      },
      {
        locationId: "h7",
        name: "Golconda Fort",
        category: "landmark",
        latitude: 17.3833,
        longitude: 78.4011,
        mapX: 22,
        mapY: 60,
        pollutionMultiplier: 0.55,
        sensorAvailable: false,
        description: "16th-century Qutb Shahi fort; heritage green buffer",
      },
      {
        locationId: "h8",
        name: "LB Nagar",
        category: "residential",
        latitude: 17.3483,
        longitude: 78.5521,
        mapX: 64,
        mapY: 72,
        pollutionMultiplier: 0.82,
        sensorAvailable: false,
        description: "Eastern residential growth corridor; highway proximity",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  CHENNAI  (lat 13.08, lng 80.27)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "chennai",
    center: { lat: 13.0827, lng: 80.2707 },
    zoom: 12,
    waterBodies: [
      { id: "cnw1", name: "Adyar River", x: 50, y: 76, latitude: 13.0067, longitude: 80.2572 },
      {
        id: "cnw2",
        name: "Pallikaranai Marsh",
        x: 60,
        y: 84,
        latitude: 12.939,
        longitude: 80.2146,
      },
      { id: "cnw3", name: "Cooum River", x: 36, y: 48, latitude: 13.07, longitude: 80.265 },
    ],
    zones: { residential: 56, industrial: 16, commercial: 20, greenCover: 8 },
    locations: [
      {
        locationId: "cn1",
        name: "Ambattur Industrial Estate",
        category: "industrial",
        latitude: 13.1099,
        longitude: 80.1615,
        mapX: 22,
        mapY: 26,
        pollutionMultiplier: 1.4,
        sensorAvailable: true,
        description: "State's largest SIDCO estate; auto-parts & electronics manufacturing",
      },
      {
        locationId: "cn2",
        name: "Marina Beach",
        category: "landmark",
        latitude: 13.05,
        longitude: 80.2824,
        mapX: 70,
        mapY: 56,
        pollutionMultiplier: 0.48,
        sensorAvailable: false,
        description: "World's second-longest urban beach; sea breeze ventilation",
      },
      {
        locationId: "cn3",
        name: "T Nagar",
        category: "commercial",
        latitude: 13.0418,
        longitude: 80.2341,
        mapX: 48,
        mapY: 60,
        pollutionMultiplier: 1.08,
        sensorAvailable: true,
        description: "Densest retail district in Asia; extreme pedestrian & vehicle load",
      },
      {
        locationId: "cn4",
        name: "Manali Industrial Zone",
        category: "industrial",
        latitude: 13.1627,
        longitude: 80.2615,
        mapX: 44,
        mapY: 16,
        pollutionMultiplier: 1.45,
        sensorAvailable: true,
        description: "Oil refinery & fertiliser complex; SO₂ & PM₂.₅ critical zone",
      },
      {
        locationId: "cn5",
        name: "Adyar",
        category: "residential",
        latitude: 13.0012,
        longitude: 80.2565,
        mapX: 54,
        mapY: 78,
        pollutionMultiplier: 0.72,
        sensorAvailable: false,
        description: "Southern residential suburb; Adyar River estuary zone",
      },
      {
        locationId: "cn6",
        name: "Koyambedu",
        category: "commercial",
        latitude: 13.0694,
        longitude: 80.1948,
        mapX: 34,
        mapY: 40,
        pollutionMultiplier: 1.12,
        sensorAvailable: true,
        description: "Wholesale market hub; heavy goods vehicle concentration",
      },
      {
        locationId: "cn7",
        name: "Pallikaranai Marsh",
        category: "water",
        latitude: 12.939,
        longitude: 80.2146,
        mapX: 60,
        mapY: 86,
        pollutionMultiplier: 0.22,
        sensorAvailable: true,
        description: "Protected freshwater wetland; biodiversity monitoring station",
      },
      {
        locationId: "cn8",
        name: "Anna Nagar",
        category: "residential",
        latitude: 13.085,
        longitude: 80.2101,
        mapX: 36,
        mapY: 36,
        pollutionMultiplier: 0.8,
        sensorAvailable: false,
        description: "Planned residential layout; above-average green cover for the city",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  PUNE  (lat 18.52, lng 73.85)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "pune",
    center: { lat: 18.5204, lng: 73.8567 },
    zoom: 12,
    waterBodies: [
      { id: "pw1", name: "Mula River", x: 38, y: 36, latitude: 18.56, longitude: 73.8467 },
      { id: "pw2", name: "Mutha River", x: 44, y: 54, latitude: 18.53, longitude: 73.86 },
      { id: "pw3", name: "Pashan Lake", x: 20, y: 44, latitude: 18.535, longitude: 73.793 },
    ],
    zones: { residential: 52, industrial: 22, commercial: 18, greenCover: 8 },
    locations: [
      {
        locationId: "p1",
        name: "Pimpri-Chinchwad",
        category: "industrial",
        latitude: 18.6298,
        longitude: 73.7997,
        mapX: 22,
        mapY: 22,
        pollutionMultiplier: 1.42,
        sensorAvailable: true,
        description: "Auto-industrial hub; Tata & Bajaj plants; PM₁₀ critical node",
      },
      {
        locationId: "p2",
        name: "Hinjewadi",
        category: "commercial",
        latitude: 18.5912,
        longitude: 73.7389,
        mapX: 16,
        mapY: 38,
        pollutionMultiplier: 0.88,
        sensorAvailable: true,
        description: "Rajiv Gandhi Infotech Park Phase I–III; rising commuter load",
      },
      {
        locationId: "p3",
        name: "FC Road",
        category: "commercial",
        latitude: 18.5238,
        longitude: 73.84,
        mapX: 44,
        mapY: 46,
        pollutionMultiplier: 0.98,
        sensorAvailable: false,
        description: "Fergusson College Road; busy F&B & retail artery",
      },
      {
        locationId: "p4",
        name: "Bhosari MIDC",
        category: "industrial",
        latitude: 18.6316,
        longitude: 73.8575,
        mapX: 34,
        mapY: 20,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "MIDC estate; defence & aerospace manufacturing cluster",
      },
      {
        locationId: "p5",
        name: "Mula River Bank",
        category: "water",
        latitude: 18.56,
        longitude: 73.8467,
        mapX: 40,
        mapY: 36,
        pollutionMultiplier: 0.28,
        sensorAvailable: true,
        description: "Mula river confluence point; effluent-discharge monitoring site",
      },
      {
        locationId: "p6",
        name: "Koregaon Park",
        category: "residential",
        latitude: 18.5362,
        longitude: 73.8931,
        mapX: 58,
        mapY: 44,
        pollutionMultiplier: 0.75,
        sensorAvailable: false,
        description: "Upscale residential & hospitality zone; OSHO ashram precinct",
      },
      {
        locationId: "p7",
        name: "Sinhagad Fort",
        category: "landmark",
        latitude: 18.3667,
        longitude: 73.7553,
        mapX: 24,
        mapY: 80,
        pollutionMultiplier: 0.38,
        sensorAvailable: false,
        description: "Sahyadri hill fort; cleanest AQI node in the Pune region",
      },
      {
        locationId: "p8",
        name: "Kothrud",
        category: "residential",
        latitude: 18.5074,
        longitude: 73.8074,
        mapX: 30,
        mapY: 58,
        pollutionMultiplier: 0.82,
        sensorAvailable: false,
        description: "Large planned residential area; moderate industrial proximity",
      },
      {
        locationId: "p9",
        name: "Hadapsar",
        category: "industrial",
        latitude: 18.5089,
        longitude: 73.926,
        mapX: 68,
        mapY: 58,
        pollutionMultiplier: 1.22,
        sensorAvailable: true,
        description: "Magarpatta & Fursungi; fast-growing industrial-residential mix",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  KOLKATA  (lat 22.57, lng 88.36)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "kolkata",
    center: { lat: 22.5726, lng: 88.3639 },
    zoom: 12,
    waterBodies: [
      { id: "kw1", name: "Hooghly River", x: 28, y: 42, latitude: 22.584, longitude: 88.3428 },
      { id: "kw2", name: "East Calcutta Wetlands", x: 72, y: 58, latitude: 22.5, longitude: 88.45 },
    ],
    zones: { residential: 58, industrial: 20, commercial: 16, greenCover: 6 },
    locations: [
      {
        locationId: "k1",
        name: "Howrah Bridge",
        category: "landmark",
        latitude: 22.5851,
        longitude: 88.3468,
        mapX: 36,
        mapY: 40,
        pollutionMultiplier: 1.05,
        sensorAvailable: true,
        description: "Iconic cantilever bridge; ambient NO₂ and PM hotspot",
      },
      {
        locationId: "k2",
        name: "Tangra",
        category: "industrial",
        latitude: 22.5514,
        longitude: 88.3915,
        mapX: 66,
        mapY: 52,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "Leather tannery cluster; chromium & effluent monitoring site",
      },
      {
        locationId: "k3",
        name: "Park Street",
        category: "commercial",
        latitude: 22.551,
        longitude: 88.3519,
        mapX: 46,
        mapY: 56,
        pollutionMultiplier: 0.95,
        sensorAvailable: false,
        description: "Cultural & F&B avenue; moderate vehicle density",
      },
      {
        locationId: "k4",
        name: "Hooghly River",
        category: "water",
        latitude: 22.584,
        longitude: 88.3428,
        mapX: 28,
        mapY: 38,
        pollutionMultiplier: 0.24,
        sensorAvailable: true,
        description: "Ganges distributary; industrial effluent entry point monitoring",
      },
      {
        locationId: "k5",
        name: "Salt Lake City",
        category: "commercial",
        latitude: 22.5804,
        longitude: 88.4323,
        mapX: 70,
        mapY: 26,
        pollutionMultiplier: 0.85,
        sensorAvailable: false,
        description: "IT sector V & Sector III; low industrial, higher vehicular load",
      },
      {
        locationId: "k6",
        name: "Maidan",
        category: "park",
        latitude: 22.557,
        longitude: 88.3418,
        mapX: 42,
        mapY: 52,
        pollutionMultiplier: 0.38,
        sensorAvailable: false,
        description: "1,000-acre lungs of Kolkata; lowest AQI in the metropolitan area",
      },
      {
        locationId: "k7",
        name: "Garden Reach",
        category: "industrial",
        latitude: 22.5205,
        longitude: 88.3121,
        mapX: 28,
        mapY: 72,
        pollutionMultiplier: 1.42,
        sensorAvailable: true,
        description: "Shipyard & engineering works; riverside heavy-industry corridor",
      },
      {
        locationId: "k8",
        name: "New Town",
        category: "commercial",
        latitude: 22.5958,
        longitude: 88.4759,
        mapX: 76,
        mapY: 20,
        pollutionMultiplier: 0.78,
        sensorAvailable: false,
        description: "Planned smart-city extension; lower density & better green cover",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  LONDON  (lat 51.50, lng -0.12)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "london",
    center: { lat: 51.5074, lng: -0.1278 },
    zoom: 11,
    waterBodies: [
      { id: "lw1", name: "River Thames", x: 44, y: 58, latitude: 51.5072, longitude: -0.1186 },
      { id: "lw2", name: "Regent's Canal", x: 38, y: 34, latitude: 51.535, longitude: -0.1465 },
      { id: "lw3", name: "Serpentine Lake", x: 36, y: 52, latitude: 51.5047, longitude: -0.1657 },
    ],
    zones: { residential: 58, industrial: 12, commercial: 22, greenCover: 8 },
    locations: [
      {
        locationId: "l1",
        name: "City of London",
        category: "commercial",
        latitude: 51.5155,
        longitude: -0.092,
        mapX: 54,
        mapY: 42,
        pollutionMultiplier: 1.02,
        sensorAvailable: true,
        description: "Square Mile financial district; below-average but NO₂ still elevated",
      },
      {
        locationId: "l2",
        name: "Canary Wharf",
        category: "commercial",
        latitude: 51.5054,
        longitude: -0.0235,
        mapX: 66,
        mapY: 44,
        pollutionMultiplier: 0.88,
        sensorAvailable: true,
        description: "Docklands financial hub; low emissions, excellent ULEZ compliance",
      },
      {
        locationId: "l3",
        name: "Heathrow Airport",
        category: "industrial",
        latitude: 51.47,
        longitude: -0.4543,
        mapX: 16,
        mapY: 58,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "Busiest airport in Europe; UK's single largest NO₂ source",
      },
      {
        locationId: "l4",
        name: "Camden",
        category: "residential",
        latitude: 51.539,
        longitude: -0.1426,
        mapX: 44,
        mapY: 26,
        pollutionMultiplier: 0.85,
        sensorAvailable: false,
        description: "Inner-city residential & arts district; moderate traffic load",
      },
      {
        locationId: "l5",
        name: "Battersea",
        category: "residential",
        latitude: 51.4813,
        longitude: -0.1451,
        mapX: 42,
        mapY: 60,
        pollutionMultiplier: 0.78,
        sensorAvailable: false,
        description: "South-bank residential; Battersea Power Station regeneration zone",
      },
      {
        locationId: "l6",
        name: "River Thames Bank",
        category: "water",
        latitude: 51.5072,
        longitude: -0.1186,
        mapX: 48,
        mapY: 58,
        pollutionMultiplier: 0.32,
        sensorAvailable: true,
        description: "Tidal Thames; continuous water-quality monitoring network",
      },
      {
        locationId: "l7",
        name: "Queen Elizabeth Park",
        category: "park",
        latitude: 51.5449,
        longitude: -0.0197,
        mapX: 68,
        mapY: 28,
        pollutionMultiplier: 0.4,
        sensorAvailable: false,
        description: "2012 Olympic legacy park; greened brownfield site",
      },
      {
        locationId: "l8",
        name: "Southall",
        category: "residential",
        latitude: 51.5063,
        longitude: -0.3717,
        mapX: 20,
        mapY: 52,
        pollutionMultiplier: 1.1,
        sensorAvailable: false,
        description: "West London residential suburb; elevated PM from M4/M25 proximity",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  NEW YORK  (lat 40.71, lng -74.00)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "newyork",
    center: { lat: 40.7128, lng: -74.006 },
    zoom: 11,
    waterBodies: [
      { id: "nyw1", name: "Hudson River", x: 30, y: 50, latitude: 40.7143, longitude: -74.022 },
      { id: "nyw2", name: "East River", x: 58, y: 44, latitude: 40.75, longitude: -73.96 },
      { id: "nyw3", name: "Jamaica Bay", x: 72, y: 70, latitude: 40.61, longitude: -73.8352 },
    ],
    zones: { residential: 52, industrial: 16, commercial: 24, greenCover: 8 },
    locations: [
      {
        locationId: "ny1",
        name: "Midtown Manhattan",
        category: "commercial",
        latitude: 40.7549,
        longitude: -73.984,
        mapX: 48,
        mapY: 34,
        pollutionMultiplier: 1.05,
        sensorAvailable: true,
        description: "Times Square & Grand Central; pedestrian canyon with trapped PM",
      },
      {
        locationId: "ny2",
        name: "South Bronx",
        category: "industrial",
        latitude: 40.8173,
        longitude: -73.927,
        mapX: 54,
        mapY: 20,
        pollutionMultiplier: 1.35,
        sensorAvailable: true,
        description: "Environmental justice hotspot; waste transfer & expressway PM",
      },
      {
        locationId: "ny3",
        name: "Red Hook, Brooklyn",
        category: "industrial",
        latitude: 40.6749,
        longitude: -74.0013,
        mapX: 44,
        mapY: 60,
        pollutionMultiplier: 1.28,
        sensorAvailable: true,
        description: "Port container terminal & industrial waterfront zone",
      },
      {
        locationId: "ny4",
        name: "Staten Island North",
        category: "residential",
        latitude: 40.642,
        longitude: -74.0776,
        mapX: 28,
        mapY: 72,
        pollutionMultiplier: 0.7,
        sensorAvailable: false,
        description: "Residential borough; lowest PM₂.₅ among the five boroughs",
      },
      {
        locationId: "ny5",
        name: "Hudson River Waterfront",
        category: "water",
        latitude: 40.7143,
        longitude: -74.022,
        mapX: 32,
        mapY: 50,
        pollutionMultiplier: 0.3,
        sensorAvailable: true,
        description: "Estuarine ecosystem; EPA Superfund legacy site monitoring",
      },
      {
        locationId: "ny6",
        name: "Central Park",
        category: "park",
        latitude: 40.7851,
        longitude: -73.9683,
        mapX: 46,
        mapY: 26,
        pollutionMultiplier: 0.38,
        sensorAvailable: false,
        description: "843-acre urban lung; consistently lowest AQI in Manhattan",
      },
      {
        locationId: "ny7",
        name: "JFK Airport Zone",
        category: "industrial",
        latitude: 40.6413,
        longitude: -73.7781,
        mapX: 74,
        mapY: 66,
        pollutionMultiplier: 1.32,
        sensorAvailable: true,
        description: "International airport & cargo hub; ultrafine particle corridor",
      },
      {
        locationId: "ny8",
        name: "Flushing, Queens",
        category: "commercial",
        latitude: 40.7675,
        longitude: -73.833,
        mapX: 68,
        mapY: 36,
        pollutionMultiplier: 0.95,
        sensorAvailable: false,
        description: "Dense commercial-residential mix; 7 subway line node",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  SINGAPORE  (lat 1.35, lng 103.82)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "singapore",
    center: { lat: 1.3521, lng: 103.8198 },
    zoom: 12,
    waterBodies: [
      {
        id: "sgw1",
        name: "MacRitchie Reservoir",
        x: 44,
        y: 26,
        latitude: 1.3456,
        longitude: 103.8175,
      },
      { id: "sgw2", name: "Marina Reservoir", x: 58, y: 56, latitude: 1.287, longitude: 103.861 },
      { id: "sgw3", name: "Kallang River", x: 52, y: 40, latitude: 1.305, longitude: 103.87 },
    ],
    zones: { residential: 46, industrial: 22, commercial: 20, greenCover: 12 },
    locations: [
      {
        locationId: "sg1",
        name: "Jurong Island",
        category: "industrial",
        latitude: 1.266,
        longitude: 103.7,
        mapX: 16,
        mapY: 66,
        pollutionMultiplier: 1.45,
        sensorAvailable: true,
        description: "Petrochemical & refinery complex; Singapore's largest industrial zone",
      },
      {
        locationId: "sg2",
        name: "Marina Bay",
        category: "commercial",
        latitude: 1.2816,
        longitude: 103.8636,
        mapX: 58,
        mapY: 54,
        pollutionMultiplier: 0.82,
        sensorAvailable: true,
        description: "CBD & Gardens by the Bay; well-ventilated coastal site",
      },
      {
        locationId: "sg3",
        name: "Buona Vista",
        category: "commercial",
        latitude: 1.3068,
        longitude: 103.7902,
        mapX: 34,
        mapY: 46,
        pollutionMultiplier: 0.85,
        sensorAvailable: false,
        description: "one-north R&D park; Biopolis & Fusionopolis precinct",
      },
      {
        locationId: "sg4",
        name: "Changi Airport",
        category: "industrial",
        latitude: 1.3644,
        longitude: 103.9915,
        mapX: 84,
        mapY: 36,
        pollutionMultiplier: 1.3,
        sensorAvailable: true,
        description: "World's most awarded airport; aviation emissions monitoring zone",
      },
      {
        locationId: "sg5",
        name: "MacRitchie Reservoir",
        category: "water",
        latitude: 1.3456,
        longitude: 103.8175,
        mapX: 44,
        mapY: 26,
        pollutionMultiplier: 0.18,
        sensorAvailable: true,
        description: "Central Catchment Nature Reserve; cleanest air node on the island",
      },
      {
        locationId: "sg6",
        name: "Sentosa Island",
        category: "landmark",
        latitude: 1.2494,
        longitude: 103.8303,
        mapX: 48,
        mapY: 76,
        pollutionMultiplier: 0.45,
        sensorAvailable: false,
        description: "Resort & entertainment island; sea-breeze dispersion advantage",
      },
      {
        locationId: "sg7",
        name: "Woodlands",
        category: "residential",
        latitude: 1.4382,
        longitude: 103.7889,
        mapX: 34,
        mapY: 14,
        pollutionMultiplier: 0.72,
        sensorAvailable: false,
        description: "Northern HDB new town; Johor Strait waterfront",
      },
      {
        locationId: "sg8",
        name: "Tuas West",
        category: "industrial",
        latitude: 1.319,
        longitude: 103.6406,
        mapX: 10,
        mapY: 48,
        pollutionMultiplier: 1.38,
        sensorAvailable: true,
        description: "Second-phase industrial expansion; port & logistics corridor",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  TOKYO  (lat 35.68, lng 139.69)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "tokyo",
    center: { lat: 35.6762, lng: 139.6503 },
    zoom: 11,
    waterBodies: [
      { id: "tw1", name: "Sumida River", x: 58, y: 36, latitude: 35.709, longitude: 139.805 },
      { id: "tw2", name: "Tokyo Bay", x: 58, y: 68, latitude: 35.62, longitude: 139.78 },
      { id: "tw3", name: "Tama River", x: 18, y: 64, latitude: 35.61, longitude: 139.53 },
    ],
    zones: { residential: 54, industrial: 18, commercial: 24, greenCover: 4 },
    locations: [
      {
        locationId: "t1",
        name: "Shinjuku",
        category: "commercial",
        latitude: 35.6938,
        longitude: 139.7034,
        mapX: 38,
        mapY: 40,
        pollutionMultiplier: 1.05,
        sensorAvailable: true,
        description: "Densest commercial hub in Japan; car & rail interchange",
      },
      {
        locationId: "t2",
        name: "Shibuya",
        category: "commercial",
        latitude: 35.6595,
        longitude: 139.7004,
        mapX: 40,
        mapY: 56,
        pollutionMultiplier: 0.98,
        sensorAvailable: false,
        description: "Major shopping & entertainment crossroads; PM₂.₅ benchmark site",
      },
      {
        locationId: "t3",
        name: "Koto Ward",
        category: "industrial",
        latitude: 35.6728,
        longitude: 139.8172,
        mapX: 68,
        mapY: 44,
        pollutionMultiplier: 1.28,
        sensorAvailable: true,
        description: "Eastern industrial waterfront; historically highest NOx in Tokyo",
      },
      {
        locationId: "t4",
        name: "Sumida River",
        category: "water",
        latitude: 35.709,
        longitude: 139.805,
        mapX: 58,
        mapY: 32,
        pollutionMultiplier: 0.3,
        sensorAvailable: true,
        description: "Urban river; continuous water & air quality monitoring network",
      },
      {
        locationId: "t5",
        name: "Asakusa",
        category: "landmark",
        latitude: 35.7148,
        longitude: 139.7967,
        mapX: 56,
        mapY: 28,
        pollutionMultiplier: 0.7,
        sensorAvailable: false,
        description: "Senso-ji temple district; heritage tourism & traditional crafts",
      },
      {
        locationId: "t6",
        name: "Shinagawa",
        category: "commercial",
        latitude: 35.6284,
        longitude: 139.7387,
        mapX: 46,
        mapY: 68,
        pollutionMultiplier: 0.92,
        sensorAvailable: false,
        description: "Shinkansen gateway; large-scale office & hotel cluster",
      },
      {
        locationId: "t7",
        name: "Chiba Coastal",
        category: "industrial",
        latitude: 35.6073,
        longitude: 140.1064,
        mapX: 82,
        mapY: 58,
        pollutionMultiplier: 1.35,
        sensorAvailable: true,
        description: "Chiba steel & petrochemical corridor; JX Nippon refinery",
      },
      {
        locationId: "t8",
        name: "Odaiba",
        category: "commercial",
        latitude: 35.627,
        longitude: 139.7761,
        mapX: 56,
        mapY: 62,
        pollutionMultiplier: 0.75,
        sensorAvailable: false,
        description: "Artificial island; open-air retail & exhibition zone",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  //  DUBAI  (lat 25.20, lng 55.27)
  // ──────────────────────────────────────────────────────────────────────────
  {
    cityId: "dubai",
    center: { lat: 25.2048, lng: 55.2708 },
    zoom: 12,
    waterBodies: [
      { id: "dbw1", name: "Dubai Creek", x: 52, y: 36, latitude: 25.2578, longitude: 55.3062 },
      {
        id: "dbw2",
        name: "Arabian Gulf Coastline",
        x: 26,
        y: 64,
        latitude: 25.08,
        longitude: 55.13,
      },
      {
        id: "dbw3",
        name: "Palm Jumeirah Lagoon",
        x: 24,
        y: 56,
        latitude: 25.1124,
        longitude: 55.139,
      },
    ],
    zones: { residential: 38, industrial: 28, commercial: 28, greenCover: 6 },
    locations: [
      {
        locationId: "db1",
        name: "Jebel Ali Port & JAFZA",
        category: "industrial",
        latitude: 24.9857,
        longitude: 55.0632,
        mapX: 10,
        mapY: 58,
        pollutionMultiplier: 1.48,
        sensorAvailable: true,
        description: "World's 9th busiest port + JAFZA free zone; highest marine PM in UAE",
      },
      {
        locationId: "db2",
        name: "Downtown Dubai",
        category: "commercial",
        latitude: 25.1972,
        longitude: 55.2744,
        mapX: 48,
        mapY: 50,
        pollutionMultiplier: 0.95,
        sensorAvailable: true,
        description: "Burj Khalifa district; high-rise canyon effect on pollutants",
      },
      {
        locationId: "db3",
        name: "Dubai Marina",
        category: "commercial",
        latitude: 25.0763,
        longitude: 55.1308,
        mapX: 26,
        mapY: 62,
        pollutionMultiplier: 0.88,
        sensorAvailable: false,
        description: "Waterfront residential & dining zone; sea breeze advantage",
      },
      {
        locationId: "db4",
        name: "Sharjah Industrial",
        category: "industrial",
        latitude: 25.334,
        longitude: 55.4197,
        mapX: 80,
        mapY: 22,
        pollutionMultiplier: 1.42,
        sensorAvailable: true,
        description: "UAE–Sharjah industrial belt; cement & metal works cluster",
      },
      {
        locationId: "db5",
        name: "Dubai Creek",
        category: "water",
        latitude: 25.2578,
        longitude: 55.3062,
        mapX: 54,
        mapY: 34,
        pollutionMultiplier: 0.28,
        sensorAvailable: true,
        description: "Historic tidal inlet; sediment and salinity monitoring point",
      },
      {
        locationId: "db6",
        name: "Business Bay",
        category: "commercial",
        latitude: 25.1854,
        longitude: 55.2707,
        mapX: 52,
        mapY: 54,
        pollutionMultiplier: 1.0,
        sensorAvailable: false,
        description: "High-rise CBD adjacent to Downtown; construction phase emissions",
      },
      {
        locationId: "db7",
        name: "Al Quoz Industrial",
        category: "industrial",
        latitude: 25.1372,
        longitude: 55.2252,
        mapX: 36,
        mapY: 64,
        pollutionMultiplier: 1.35,
        sensorAvailable: true,
        description: "Mid-city industrial zone; car workshops, paint shops & warehouses",
      },
      {
        locationId: "db8",
        name: "Dubai International Airport",
        category: "industrial",
        latitude: 25.2532,
        longitude: 55.3657,
        mapX: 60,
        mapY: 30,
        pollutionMultiplier: 1.28,
        sensorAvailable: true,
        description: "World's busiest international airport; aviation emission corridor",
      },
    ],
  },
];

// ─── Sensor-type derivation (Phase 2 GIS upgrade) ─────────────────────────────
// Maps each location's existing, real `category` + `sensorAvailable` fields to
// a device/event-axis `sensorType` used for marker styling on the new GIS map.
// This is a deterministic rule over real seed data — not invented per-row.
// Explicit `sensorType` on a LocationSeed always wins.
function deriveSensorType(loc: LocationSeed): SensorType {
  if (loc.sensorType) return loc.sensorType;
  if (!loc.sensorAvailable) return "environmental";

  switch (loc.category) {
    case "water":
      return "water";
    case "industrial":
      return "industrial";
    case "commercial":
      // Commercial zones with a deployed sensor are predominantly traffic-load
      // monitoring points in this dataset (CBD corridors, junctions, transit hubs).
      return "traffic";
    case "residential":
    case "park":
    case "landmark":
    default:
      return "environmental";
  }
}

// ─── Upsert helper ────────────────────────────────────────────────────────────
export async function seedMapData(): Promise<void> {
  console.log("[MapSeed] Starting map location seed …");

  for (const city of CITY_MAP_SEED) {
    // 1. Upsert CityMapConfig
    await CityMapConfig.findOneAndUpdate(
      { cityId: city.cityId },
      {
        cityId: city.cityId,
        center: city.center,
        zoom: city.zoom,
        bearing: city.bearing ?? 0,
        pitch: city.pitch ?? 0,
        waterBodies: city.waterBodies,
        zones: city.zones,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );

    // 2. Upsert each MapLocation
    for (const loc of city.locations) {
      await MapLocation.findOneAndUpdate(
        { cityId: city.cityId, locationId: loc.locationId },
        {
          cityId: city.cityId,
          locationId: loc.locationId,
          name: loc.name,
          category: loc.category,
          latitude: loc.latitude,
          longitude: loc.longitude,
          mapX: loc.mapX,
          mapY: loc.mapY,
          pollutionMultiplier: loc.pollutionMultiplier,
          sensorAvailable: loc.sensorAvailable,
          sensorType: deriveSensorType(loc),
          description: loc.description,
        },
        { upsert: true, new: true, setDefaultsOnInsert: true },
      );
    }

    console.log(
      `[MapSeed]  ✓ ${city.cityId} — ${city.locations.length} locations, ${city.waterBodies.length} water bodies`,
    );
  }

  console.log(`[MapSeed] Done. ${CITY_MAP_SEED.length} cities seeded.`);
}

// ─── Standalone entry-point ───────────────────────────────────────────────────
if (require.main === module) {
  (async () => {
    const uri = process.env.MONGODB_URI || "mongodb://localhost:27017/greenguard";
    await mongoose.connect(uri);
    console.log("[MapSeed] Connected to MongoDB");
    await seedMapData();
    await mongoose.disconnect();
    console.log("[MapSeed] Disconnected. Exiting.");
    process.exit(0);
  })();
}
