/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuthoritiesRouteImport } from './routes/admin.authorities'
import { Route as AdminAuthorityRequestsRouteImport } from './routes/admin.authority-requests'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminPlatformHealthRouteImport } from './routes/admin.platform-health'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as HelpAboutRouteImport } from './routes/help.about'
import { Route as HelpCommunityRouteImport } from './routes/help.community'
import { Route as HelpFeedbackRouteImport } from './routes/help.feedback'
import { Route as HelpKnowledgeBaseRouteImport } from './routes/help.knowledge-base'
import { Route as HelpStatusRouteImport } from './routes/help.status'
import { Route as HelpSupportRouteImport } from './routes/help.support'
import { Route as HelpTutorialsRouteImport } from './routes/help.tutorials'
import { Route as HelpWhatsNewRouteImport } from './routes/help.whats-new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthoritiesRoute = AdminAuthoritiesRouteImport.update({
  id: '/authorities',
  path: '/authorities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthorityRequestsRoute = AdminAuthorityRequestsRouteImport.update({
  id: '/authority-requests',
  path: '/authority-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformHealthRoute = AdminPlatformHealthRouteImport.update({
  id: '/platform-health',
  path: '/platform-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const HelpAboutRoute = HelpAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HelpRoute,
} as any)
const HelpCommunityRoute = HelpCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => HelpRoute,
} as any)
const HelpFeedbackRoute = HelpFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => HelpRoute,
} as any)
const HelpKnowledgeBaseRoute = HelpKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => HelpRoute,
} as any)
const HelpStatusRoute = HelpStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => HelpRoute,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => HelpRoute,
} as any)
const HelpTutorialsRoute = HelpTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => HelpRoute,
} as any)
const HelpWhatsNewRoute = HelpWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => HelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/environment': typeof EnvironmentRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/authority-requests': typeof AdminAuthorityRequestsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/help/about': typeof HelpAboutRoute
  '/help/community': typeof HelpCommunityRoute
  '/help/feedback': typeof HelpFeedbackRoute
  '/help/knowledge-base': typeof HelpKnowledgeBaseRoute
  '/help/status': typeof HelpStatusRoute
  '/help/support': typeof HelpSupportRoute
  '/help/tutorials': typeof HelpTutorialsRoute
  '/help/whats-new': typeof HelpWhatsNewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/environment': typeof EnvironmentRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/authority-requests': typeof AdminAuthorityRequestsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/help/about': typeof HelpAboutRoute
  '/help/community': typeof HelpCommunityRoute
  '/help/feedback': typeof HelpFeedbackRoute
  '/help/knowledge-base': typeof HelpKnowledgeBaseRoute
  '/help/status': typeof HelpStatusRoute
  '/help/support': typeof HelpSupportRoute
  '/help/tutorials': typeof HelpTutorialsRoute
  '/help/whats-new': typeof HelpWhatsNewRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/environment': typeof EnvironmentRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/authority-requests': typeof AdminAuthorityRequestsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/help/about': typeof HelpAboutRoute
  '/help/community': typeof HelpCommunityRoute
  '/help/feedback': typeof HelpFeedbackRoute
  '/help/knowledge-base': typeof HelpKnowledgeBaseRoute
  '/help/status': typeof HelpStatusRoute
  '/help/support': typeof HelpSupportRoute
  '/help/tutorials': typeof HelpTutorialsRoute
  '/help/whats-new': typeof HelpWhatsNewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/citizen'
    | '/command-center'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/docs'
    | '/environment'
    | '/forecast'
    | '/forgot-password'
    | '/help'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sustainability'
    | '/terms'
    | '/admin/authorities'
    | '/admin/authority-requests'
    | '/admin/cities'
    | '/admin/complaints'
    | '/admin/platform-health'
    | '/admin/profile'
    | '/admin/users'
    | '/help/about'
    | '/help/community'
    | '/help/feedback'
    | '/help/knowledge-base'
    | '/help/status'
    | '/help/support'
    | '/help/tutorials'
    | '/help/whats-new'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/citizen'
    | '/command-center'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/docs'
    | '/environment'
    | '/forecast'
    | '/forgot-password'
    | '/help'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sustainability'
    | '/terms'
    | '/admin/authorities'
    | '/admin/authority-requests'
    | '/admin/cities'
    | '/admin/complaints'
    | '/admin/platform-health'
    | '/admin/profile'
    | '/admin/users'
    | '/help/about'
    | '/help/community'
    | '/help/feedback'
    | '/help/knowledge-base'
    | '/help/status'
    | '/help/support'
    | '/help/tutorials'
    | '/help/whats-new'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/citizen'
    | '/command-center'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/docs'
    | '/environment'
    | '/forecast'
    | '/forgot-password'
    | '/help'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sustainability'
    | '/terms'
    | '/admin/authorities'
    | '/admin/authority-requests'
    | '/admin/cities'
    | '/admin/complaints'
    | '/admin/platform-health'
    | '/admin/profile'
    | '/admin/users'
    | '/help/about'
    | '/help/community'
    | '/help/feedback'
    | '/help/knowledge-base'
    | '/help/status'
    | '/help/support'
    | '/help/tutorials'
    | '/help/whats-new'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitizenRoute: typeof CitizenRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ContactRoute: typeof ContactRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  EnvironmentRoute: typeof EnvironmentRoute
  ForecastRoute: typeof ForecastRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRouteWithChildren
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authorities': {
      id: '/admin/authorities'
      path: '/authorities'
      fullPath: '/admin/authorities'
      preLoaderRoute: typeof AdminAuthoritiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authority-requests': {
      id: '/admin/authority-requests'
      path: '/authority-requests'
      fullPath: '/admin/authority-requests'
      preLoaderRoute: typeof AdminAuthorityRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-health': {
      id: '/admin/platform-health'
      path: '/platform-health'
      fullPath: '/admin/platform-health'
      preLoaderRoute: typeof AdminPlatformHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/help/about': {
      id: '/help/about'
      path: '/about'
      fullPath: '/help/about'
      preLoaderRoute: typeof HelpAboutRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/community': {
      id: '/help/community'
      path: '/community'
      fullPath: '/help/community'
      preLoaderRoute: typeof HelpCommunityRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/feedback': {
      id: '/help/feedback'
      path: '/feedback'
      fullPath: '/help/feedback'
      preLoaderRoute: typeof HelpFeedbackRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/knowledge-base': {
      id: '/help/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/help/knowledge-base'
      preLoaderRoute: typeof HelpKnowledgeBaseRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/status': {
      id: '/help/status'
      path: '/status'
      fullPath: '/help/status'
      preLoaderRoute: typeof HelpStatusRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/support': {
      id: '/help/support'
      path: '/support'
      fullPath: '/help/support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/tutorials': {
      id: '/help/tutorials'
      path: '/tutorials'
      fullPath: '/help/tutorials'
      preLoaderRoute: typeof HelpTutorialsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/whats-new': {
      id: '/help/whats-new'
      path: '/whats-new'
      fullPath: '/help/whats-new'
      preLoaderRoute: typeof HelpWhatsNewRouteImport
      parentRoute: typeof HelpRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuthoritiesRoute: typeof AdminAuthoritiesRoute
  AdminAuthorityRequestsRoute: typeof AdminAuthorityRequestsRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminPlatformHealthRoute: typeof AdminPlatformHealthRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthoritiesRoute: AdminAuthoritiesRoute,
  AdminAuthorityRequestsRoute: AdminAuthorityRequestsRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminPlatformHealthRoute: AdminPlatformHealthRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HelpRouteChildren {
  HelpAboutRoute: typeof HelpAboutRoute
  HelpCommunityRoute: typeof HelpCommunityRoute
  HelpFeedbackRoute: typeof HelpFeedbackRoute
  HelpKnowledgeBaseRoute: typeof HelpKnowledgeBaseRoute
  HelpStatusRoute: typeof HelpStatusRoute
  HelpSupportRoute: typeof HelpSupportRoute
  HelpTutorialsRoute: typeof HelpTutorialsRoute
  HelpWhatsNewRoute: typeof HelpWhatsNewRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpAboutRoute: HelpAboutRoute,
  HelpCommunityRoute: HelpCommunityRoute,
  HelpFeedbackRoute: HelpFeedbackRoute,
  HelpKnowledgeBaseRoute: HelpKnowledgeBaseRoute,
  HelpStatusRoute: HelpStatusRoute,
  HelpSupportRoute: HelpSupportRoute,
  HelpTutorialsRoute: HelpTutorialsRoute,
  HelpWhatsNewRoute: HelpWhatsNewRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CitizenRoute: CitizenRoute,
  CommandCenterRoute: CommandCenterRoute,
  ContactRoute: ContactRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  EnvironmentRoute: EnvironmentRoute,
  ForecastRoute: ForecastRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRouteWithChildren,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulatorRoute: SimulatorRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
