/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuthoritiesRouteImport } from './routes/admin.authorities'
import { Route as AdminAuthorityManagementRouteImport } from './routes/admin.authority-management'
import { Route as AdminAuthorityRequestsRouteImport } from './routes/admin.authority-requests'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminCityManagementRouteImport } from './routes/admin.city-management'
import { Route as AdminComplaintManagementRouteImport } from './routes/admin.complaint-management'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminEnvironmentalMonitoringRouteImport } from './routes/admin.environmental-monitoring'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as AdminPlatformAdministrationRouteImport } from './routes/admin.platform-administration'
import { Route as AdminPlatformHealthRouteImport } from './routes/admin.platform-health'
import { Route as AdminPlatformSettingsRouteImport } from './routes/admin.platform-settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSecurityCenterRouteImport } from './routes/admin.security-center'
import { Route as AdminUserManagementRouteImport } from './routes/admin.user-management'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as HelpAboutRouteImport } from './routes/help.about'
import { Route as HelpCommunityRouteImport } from './routes/help.community'
import { Route as HelpFeedbackRouteImport } from './routes/help.feedback'
import { Route as HelpKnowledgeBaseRouteImport } from './routes/help.knowledge-base'
import { Route as HelpStatusRouteImport } from './routes/help.status'
import { Route as HelpSupportRouteImport } from './routes/help.support'
import { Route as HelpTutorialsRouteImport } from './routes/help.tutorials'
import { Route as HelpWhatsNewRouteImport } from './routes/help.whats-new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthoritiesRoute = AdminAuthoritiesRouteImport.update({
  id: '/authorities',
  path: '/authorities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthorityManagementRoute =
  AdminAuthorityManagementRouteImport.update({
    id: '/authority-management',
    path: '/authority-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAuthorityRequestsRoute = AdminAuthorityRequestsRouteImport.update({
  id: '/authority-requests',
  path: '/authority-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCityManagementRoute = AdminCityManagementRouteImport.update({
  id: '/city-management',
  path: '/city-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintManagementRoute =
  AdminComplaintManagementRouteImport.update({
    id: '/complaint-management',
    path: '/complaint-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnvironmentalMonitoringRoute =
  AdminEnvironmentalMonitoringRouteImport.update({
    id: '/environmental-monitoring',
    path: '/environmental-monitoring',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformAdministrationRoute =
  AdminPlatformAdministrationRouteImport.update({
    id: '/platform-administration',
    path: '/platform-administration',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPlatformHealthRoute = AdminPlatformHealthRouteImport.update({
  id: '/platform-health',
  path: '/platform-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformSettingsRoute = AdminPlatformSettingsRouteImport.update({
  id: '/platform-settings',
  path: '/platform-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityCenterRoute = AdminSecurityCenterRouteImport.update({
  id: '/security-center',
  path: '/security-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const HelpAboutRoute = HelpAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HelpRoute,
} as any)
const HelpCommunityRoute = HelpCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => HelpRoute,
} as any)
const HelpFeedbackRoute = HelpFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => HelpRoute,
} as any)
const HelpKnowledgeBaseRoute = HelpKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => HelpRoute,
} as any)
const HelpStatusRoute = HelpStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => HelpRoute,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => HelpRoute,
} as any)
const HelpTutorialsRoute = HelpTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => HelpRoute,
} as any)
const HelpWhatsNewRoute = HelpWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => HelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/environment': typeof EnvironmentRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/authority-management': typeof AdminAuthorityManagementRoute
  '/admin/authority-requests': typeof AdminAuthorityRequestsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/city-management': typeof AdminCityManagementRoute
  '/admin/complaint-management': typeof AdminComplaintManagementRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/environmental-monitoring': typeof AdminEnvironmentalMonitoringRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/platform-administration': typeof AdminPlatformAdministrationRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/platform-settings': typeof AdminPlatformSettingsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security-center': typeof AdminSecurityCenterRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/admin/users': typeof AdminUsersRoute
  '/help/about': typeof HelpAboutRoute
  '/help/community': typeof HelpCommunityRoute
  '/help/feedback': typeof HelpFeedbackRoute
  '/help/knowledge-base': typeof HelpKnowledgeBaseRoute
  '/help/status': typeof HelpStatusRoute
  '/help/support': typeof HelpSupportRoute
  '/help/tutorials': typeof HelpTutorialsRoute
  '/help/whats-new': typeof HelpWhatsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/help/': typeof HelpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/environment': typeof EnvironmentRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/authority-management': typeof AdminAuthorityManagementRoute
  '/admin/authority-requests': typeof AdminAuthorityRequestsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/city-management': typeof AdminCityManagementRoute
  '/admin/complaint-management': typeof AdminComplaintManagementRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/environmental-monitoring': typeof AdminEnvironmentalMonitoringRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/platform-administration': typeof AdminPlatformAdministrationRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/platform-settings': typeof AdminPlatformSettingsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security-center': typeof AdminSecurityCenterRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/admin/users': typeof AdminUsersRoute
  '/help/about': typeof HelpAboutRoute
  '/help/community': typeof HelpCommunityRoute
  '/help/feedback': typeof HelpFeedbackRoute
  '/help/knowledge-base': typeof HelpKnowledgeBaseRoute
  '/help/status': typeof HelpStatusRoute
  '/help/support': typeof HelpSupportRoute
  '/help/tutorials': typeof HelpTutorialsRoute
  '/help/whats-new': typeof HelpWhatsNewRoute
  '/admin': typeof AdminIndexRoute
  '/help': typeof HelpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/environment': typeof EnvironmentRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/authority-management': typeof AdminAuthorityManagementRoute
  '/admin/authority-requests': typeof AdminAuthorityRequestsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/city-management': typeof AdminCityManagementRoute
  '/admin/complaint-management': typeof AdminComplaintManagementRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/environmental-monitoring': typeof AdminEnvironmentalMonitoringRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/platform-administration': typeof AdminPlatformAdministrationRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/platform-settings': typeof AdminPlatformSettingsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security-center': typeof AdminSecurityCenterRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/admin/users': typeof AdminUsersRoute
  '/help/about': typeof HelpAboutRoute
  '/help/community': typeof HelpCommunityRoute
  '/help/feedback': typeof HelpFeedbackRoute
  '/help/knowledge-base': typeof HelpKnowledgeBaseRoute
  '/help/status': typeof HelpStatusRoute
  '/help/support': typeof HelpSupportRoute
  '/help/tutorials': typeof HelpTutorialsRoute
  '/help/whats-new': typeof HelpWhatsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/help/': typeof HelpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/citizen'
    | '/command-center'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/docs'
    | '/environment'
    | '/forecast'
    | '/forgot-password'
    | '/help'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sustainability'
    | '/terms'
    | '/verify-2fa'
    | '/admin/analytics'
    | '/admin/authorities'
    | '/admin/authority-management'
    | '/admin/authority-requests'
    | '/admin/cities'
    | '/admin/city-management'
    | '/admin/complaint-management'
    | '/admin/complaints'
    | '/admin/environmental-monitoring'
    | '/admin/platform'
    | '/admin/platform-administration'
    | '/admin/platform-health'
    | '/admin/platform-settings'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/security-center'
    | '/admin/user-management'
    | '/admin/users'
    | '/help/about'
    | '/help/community'
    | '/help/feedback'
    | '/help/knowledge-base'
    | '/help/status'
    | '/help/support'
    | '/help/tutorials'
    | '/help/whats-new'
    | '/admin/'
    | '/help/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/citizen'
    | '/command-center'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/docs'
    | '/environment'
    | '/forecast'
    | '/forgot-password'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sustainability'
    | '/terms'
    | '/verify-2fa'
    | '/admin/analytics'
    | '/admin/authorities'
    | '/admin/authority-management'
    | '/admin/authority-requests'
    | '/admin/cities'
    | '/admin/city-management'
    | '/admin/complaint-management'
    | '/admin/complaints'
    | '/admin/environmental-monitoring'
    | '/admin/platform'
    | '/admin/platform-administration'
    | '/admin/platform-health'
    | '/admin/platform-settings'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/security-center'
    | '/admin/user-management'
    | '/admin/users'
    | '/help/about'
    | '/help/community'
    | '/help/feedback'
    | '/help/knowledge-base'
    | '/help/status'
    | '/help/support'
    | '/help/tutorials'
    | '/help/whats-new'
    | '/admin'
    | '/help'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/citizen'
    | '/command-center'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/docs'
    | '/environment'
    | '/forecast'
    | '/forgot-password'
    | '/help'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sustainability'
    | '/terms'
    | '/verify-2fa'
    | '/admin/analytics'
    | '/admin/authorities'
    | '/admin/authority-management'
    | '/admin/authority-requests'
    | '/admin/cities'
    | '/admin/city-management'
    | '/admin/complaint-management'
    | '/admin/complaints'
    | '/admin/environmental-monitoring'
    | '/admin/platform'
    | '/admin/platform-administration'
    | '/admin/platform-health'
    | '/admin/platform-settings'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/security-center'
    | '/admin/user-management'
    | '/admin/users'
    | '/help/about'
    | '/help/community'
    | '/help/feedback'
    | '/help/knowledge-base'
    | '/help/status'
    | '/help/support'
    | '/help/tutorials'
    | '/help/whats-new'
    | '/admin/'
    | '/help/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitizenRoute: typeof CitizenRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ContactRoute: typeof ContactRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  EnvironmentRoute: typeof EnvironmentRoute
  ForecastRoute: typeof ForecastRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRouteWithChildren
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  Verify2faRoute: typeof Verify2faRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authorities': {
      id: '/admin/authorities'
      path: '/authorities'
      fullPath: '/admin/authorities'
      preLoaderRoute: typeof AdminAuthoritiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authority-management': {
      id: '/admin/authority-management'
      path: '/authority-management'
      fullPath: '/admin/authority-management'
      preLoaderRoute: typeof AdminAuthorityManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authority-requests': {
      id: '/admin/authority-requests'
      path: '/authority-requests'
      fullPath: '/admin/authority-requests'
      preLoaderRoute: typeof AdminAuthorityRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/city-management': {
      id: '/admin/city-management'
      path: '/city-management'
      fullPath: '/admin/city-management'
      preLoaderRoute: typeof AdminCityManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaint-management': {
      id: '/admin/complaint-management'
      path: '/complaint-management'
      fullPath: '/admin/complaint-management'
      preLoaderRoute: typeof AdminComplaintManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/environmental-monitoring': {
      id: '/admin/environmental-monitoring'
      path: '/environmental-monitoring'
      fullPath: '/admin/environmental-monitoring'
      preLoaderRoute: typeof AdminEnvironmentalMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-administration': {
      id: '/admin/platform-administration'
      path: '/platform-administration'
      fullPath: '/admin/platform-administration'
      preLoaderRoute: typeof AdminPlatformAdministrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-health': {
      id: '/admin/platform-health'
      path: '/platform-health'
      fullPath: '/admin/platform-health'
      preLoaderRoute: typeof AdminPlatformHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-settings': {
      id: '/admin/platform-settings'
      path: '/platform-settings'
      fullPath: '/admin/platform-settings'
      preLoaderRoute: typeof AdminPlatformSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-center': {
      id: '/admin/security-center'
      path: '/security-center'
      fullPath: '/admin/security-center'
      preLoaderRoute: typeof AdminSecurityCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/about': {
      id: '/help/about'
      path: '/about'
      fullPath: '/help/about'
      preLoaderRoute: typeof HelpAboutRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/community': {
      id: '/help/community'
      path: '/community'
      fullPath: '/help/community'
      preLoaderRoute: typeof HelpCommunityRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/feedback': {
      id: '/help/feedback'
      path: '/feedback'
      fullPath: '/help/feedback'
      preLoaderRoute: typeof HelpFeedbackRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/knowledge-base': {
      id: '/help/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/help/knowledge-base'
      preLoaderRoute: typeof HelpKnowledgeBaseRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/status': {
      id: '/help/status'
      path: '/status'
      fullPath: '/help/status'
      preLoaderRoute: typeof HelpStatusRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/support': {
      id: '/help/support'
      path: '/support'
      fullPath: '/help/support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/tutorials': {
      id: '/help/tutorials'
      path: '/tutorials'
      fullPath: '/help/tutorials'
      preLoaderRoute: typeof HelpTutorialsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/whats-new': {
      id: '/help/whats-new'
      path: '/whats-new'
      fullPath: '/help/whats-new'
      preLoaderRoute: typeof HelpWhatsNewRouteImport
      parentRoute: typeof HelpRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuthoritiesRoute: typeof AdminAuthoritiesRoute
  AdminAuthorityManagementRoute: typeof AdminAuthorityManagementRoute
  AdminAuthorityRequestsRoute: typeof AdminAuthorityRequestsRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminCityManagementRoute: typeof AdminCityManagementRoute
  AdminComplaintManagementRoute: typeof AdminComplaintManagementRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminEnvironmentalMonitoringRoute: typeof AdminEnvironmentalMonitoringRoute
  AdminPlatformRoute: typeof AdminPlatformRoute
  AdminPlatformAdministrationRoute: typeof AdminPlatformAdministrationRoute
  AdminPlatformHealthRoute: typeof AdminPlatformHealthRoute
  AdminPlatformSettingsRoute: typeof AdminPlatformSettingsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSecurityCenterRoute: typeof AdminSecurityCenterRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuthoritiesRoute: AdminAuthoritiesRoute,
  AdminAuthorityManagementRoute: AdminAuthorityManagementRoute,
  AdminAuthorityRequestsRoute: AdminAuthorityRequestsRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminCityManagementRoute: AdminCityManagementRoute,
  AdminComplaintManagementRoute: AdminComplaintManagementRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminEnvironmentalMonitoringRoute: AdminEnvironmentalMonitoringRoute,
  AdminPlatformRoute: AdminPlatformRoute,
  AdminPlatformAdministrationRoute: AdminPlatformAdministrationRoute,
  AdminPlatformHealthRoute: AdminPlatformHealthRoute,
  AdminPlatformSettingsRoute: AdminPlatformSettingsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSecurityCenterRoute: AdminSecurityCenterRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HelpRouteChildren {
  HelpAboutRoute: typeof HelpAboutRoute
  HelpCommunityRoute: typeof HelpCommunityRoute
  HelpFeedbackRoute: typeof HelpFeedbackRoute
  HelpKnowledgeBaseRoute: typeof HelpKnowledgeBaseRoute
  HelpStatusRoute: typeof HelpStatusRoute
  HelpSupportRoute: typeof HelpSupportRoute
  HelpTutorialsRoute: typeof HelpTutorialsRoute
  HelpWhatsNewRoute: typeof HelpWhatsNewRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpAboutRoute: HelpAboutRoute,
  HelpCommunityRoute: HelpCommunityRoute,
  HelpFeedbackRoute: HelpFeedbackRoute,
  HelpKnowledgeBaseRoute: HelpKnowledgeBaseRoute,
  HelpStatusRoute: HelpStatusRoute,
  HelpSupportRoute: HelpSupportRoute,
  HelpTutorialsRoute: HelpTutorialsRoute,
  HelpWhatsNewRoute: HelpWhatsNewRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CitizenRoute: CitizenRoute,
  CommandCenterRoute: CommandCenterRoute,
  ContactRoute: ContactRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  EnvironmentRoute: EnvironmentRoute,
  ForecastRoute: ForecastRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRouteWithChildren,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulatorRoute: SimulatorRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  Verify2faRoute: Verify2faRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
